# Proofs

## 3.1 & 3.2. Proofs Involving Negations and Conditionals

Sections 3.1 and 3.2 of *How To Prove It* present strategies for dealing with givens and goals involving negations and conditionals.  We restate those strategies here, and explain how to use them with Lean.

Section 3.1 gives two strategies for proving a goal of the form `P â†’ Q`:

#### To prove a goal of the form `P â†’ Q`:

1.  Assume `P` is true and prove `Q`.
2.  Assume `Q` is false and prove that `P` is false.

We've already seen how to carry out both of these strategies in Lean.  For the first strategy, use the `assume` tactic to introduce the assumption `P` and assign an identifier to it; Lean will automaticall set `Q` as the goal.  We can summarize the effect of using this strategy by showing how the tactic state changes if you use the tactic `assume h : P`:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
âŠ¢ P â†’ Q
```
:::

::: {.aft}
```state
>> â‹®
h : P
âŠ¢ Q
```
:::
:::

The second strategy is justified by the contrapositive law.  In Lean, you can use the `contrapos` tactic to rewrite the goal as `Â¬Q â†’ Â¬P` and then use the tactic `assume h : Â¬Q`.  The net effect of these two tactics is:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
âŠ¢ P â†’ Q
```
:::

::: {.aft}
```state
>> â‹®
h : Â¬Q
âŠ¢ Â¬P
```
:::
:::

Section 3.2 gives two strategies for using givens of the form `P â†’ Q`, with the second once again being a variation on the first based on the contrapositive law:

#### To use a given of the form `P â†’ Q`:

1.  If you are also given `P`, or you can prove that `P` is true, then you can use this given to conclude that `Q` is true.
2.  If you are also given `Â¬Q`, or you can prove that `Q` is false, then you can use this given to conclude that `P` is false.

The first strategy is the modus ponens rule of inference, and we saw in the last chapter that if you have `h1 : P â†’ Q` and `h2 : P`, then `h1 h2` is a (term-mode) proof of `Q`; often we use this rule with the `have` or `show` tactic.  For the second strategy, if you have `h1 : P â†’ Q` and `h2 : Â¬Q`, then the `contrapos at h1` tactic will change `h1` to `h1 : Â¬Q â†’ Â¬P`, and then `h1 h2` will be a proof of `Â¬P`.

All of the strategies listed above for working with conditional statements as givens or goals were illustrated in examples in the last chapter.

Section 3.2 of *HTPI* offers two strategies for proving negative goals:

#### To prove a goal of the form `Â¬P`:

1.  Reexpress the goal in some other form.
2.  Use proof by contradiction: assume `P` is true and try to deduce a contradiction.

For the first strategy, the tactics `demorgan`, `conditional`, `double_neg`, and `bicond_neg` may be useful, and we saw how those tactics work in the last chapter.  But how do you write a proof by contradiction in Lean?  The answer is to use a tactic called `by_contra`.  If the goal is `Â¬P`, then the tactic `by_contra h` will introduce the assumption `h : P` and set the goal to be `False`, like this:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
âŠ¢ Â¬P
```
:::

::: {.aft}
```state
>> â‹®
h : P
âŠ¢ False
```
:::
:::

In Lean, `False` represents a statement that is always false---that is, a contradiction, as that term is defined in Section 1.2 of *HTPI*.  The `by_contra` tactic can actually be used even if the goal is not a negative statement.  If the goal is a statement `P` that is not a negative statement, then `by_contra h` will initiate a proof by contradiction by introducing the assumption `h : Â¬P` and setting the goal to be `False`.

You will usually complete a proof by contradiction by deducing two contradictory statements---say, `h1 : Q` and `h2 : Â¬Q`.  But how do you convince Lean that the proof is over?  You must be able to prove the goal `False` from the two givens `h1` and `h2`.  There are two ways to do this.  The first is based on the fact that Lean treats a statement of the form `Â¬Q` as meaning the same thing as `Q â†’ False`.  This makes sense, because these statements are logically equivalent, as shown by the following truth table:

::: {style="margin: 0% 20%"}
| `Q` | `Â¬Q` | `(Q` | `â†’` | `False)`|
|:----------:|:----------:|-:|:-:|:-|
| F | T | F | T | &nbsp;&nbsp;[&nbsp;]{.excl} F |
| T | F | T | F | &nbsp;&nbsp;[&nbsp;]{.excl} F |
:::

Thinking of `h2 : Â¬Q` as meaning `h2 : Q â†’ False`, we can combine it with `h1 : Q` using modus ponens to deduce `False`.  In other words, `h2 h1` is a proof of `False`.

But there is a second way of completing the proof that it is worthwhile to know about.  From contradictory statements `h1 : Q` and `h2 : Â¬Q` you can validly deduce *any* statement.  This follows from the definition of a *valid argument* in Section 1.1 of *HTPI*.  According to that definition, you can validly infer a conclusion `R` from premises `h1 : Q` and `h2 : Â¬Q` if the premises cannot both be true without the conclusion also being true.  In this case, that standard is met, for the simple reason that the premises cannot both be true!  (This gives part of the answer to exercise 18 in Section 1.2 of *HTPI*.)  Thus, Lean has a rule that allows you to prove any statement from contradictory premises.  If you have `h1 : Q` and `h2 : Â¬Q`, then Lean will recognize `absurd h1 h2` as a (term-mode) proof of *any* statement.

To summarize, if you have `h1 : Q` and `h2 : Â¬Q`, then there are two ways to prove `False`.  Lean will recognize `h2 h1` as a proof of `False`, and it will recognize `absurd h1 h2` as a proof of any statement, including `False`.  Notice the difference in the order in which `h1` and `h2` are listed in these two proofs: In the first one, the negative statement `h2` must come first, just as the conditional statement must come first in an application of modus ponens.  But in a proof using `absurd`, the negative statement must come second.

To illustrate proof by contradiction in Lean, let's redo our first example from the last Chapter in a different way.  That example was based on Example 3.2.4 in *HTPI*.  We'll begin with the same first two steps, introducing two assumptions.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v2 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  **done::
```
:::

::: {.outpt}
```state
P Q R : Prop
h : P â†’ Q â†’ R
h2 : Â¬R
h3 : P
âŠ¢ Â¬Q
```
:::
:::

Now the goal is a negative statement, so we use the tactic `by_contra h4` to introduce the assumption `h4 : Q` and set the goal to be `False`:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v2 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  **done::
```
:::

::: {.outpt}
```state
P Q R : Prop
h : P â†’ Q â†’ R
h2 : Â¬R
h3 : P
h4 : Q
âŠ¢ False
```
:::
:::

Using the givens `h`, `h3`, and `h4` we can deduce first `Q â†’ R` and then `R` by two applications of modus ponens:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v2 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  have h5 : Q â†’ R := h h3
  have h6 : R := h5 h4
  **done::
```
:::

::: {.outpt}
```state
P Q R : Prop
h : P â†’ Q â†’ R
h2 : Â¬R
h3 : P
h4 : Q
h5 : Q â†’ R
h6 : R
âŠ¢ False
```
:::
:::

Now we have a contradiction: `h2 : Â¬R` and `h6 : R`.  To complete the proof, we deduce `False` from these two givens.  Either `h2 h6` or `absurd h6 h2` would be accepted by Lean as a proof of `False`:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v2 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  have h5 : Q â†’ R := h h3
  have h6 : R := h5 h4
  show False from h2 h6
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

Finally, we have two strategies for using a given that is a negative statement:

#### To use a given of the form `Â¬P`:

1.  Reexpress the given in some other form.
2.  If you are doing a proof by contradiction, you can achieve a contradiction by proving `P`, since that would contradict the given `Â¬P`.

Of course, strategy 1 suggests the use of the `demorgan`, `conditional`, `double_neg`, and `bicond_neg` tactics, if they apply.  For strategy 2, if you are doing a proof by contradiction and you have a given `h : Â¬P`, then the tactic `contradict h` will set the goal to be `P`, which will complete the proof by contradicting `h`.  In fact, this tactic can be used with any given; if you have a given `h : P`, where `P` is not a negative statement, then `contradict h` will set the goal to be `Â¬P`.  You can also follow the word `contradict` with a proof that is more complicated than a single identifier.  For example, if you have givens `h1 : P â†’ Â¬Q` and `h2 : P`, then `h1 h2` is a proof of `Â¬Q`, so the tactic `contradict h1 h2` will set the goal to be `Q`.

If you're not doing a proof by contradiction, then the tactic `contradict h with h'` will first initiate a proof by contradiction by assuming the negation of the goal, giving that assumption the identifier `h'`, and then it will set the goal to be the negation of the statement proven by `h`.  In other words, `contradict h with h'` is shorthand for `by_contra h'; contradict h`.

We can illustrate this with yet another way to write the proof from Example 3.2.4.  Our first three steps will be the same as last time:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v3 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  **done::
```
:::

::: {.outpt}
```state
P Q R : Prop
h : P â†’ Q â†’ R
h2 : Â¬R
h3 : P
h4 : Q
âŠ¢ False
```
:::
:::

Since we are now doing a proof by contradiction and the given `h2 : Â¬R` is a negative statement, a likely way to proceed is to try to prove `R`, which would contradict `h2`.  So we use the tactic `contradict h2`:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v3 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  contradict h2
  **done::
```
:::

::: {.outpt}
```state
P Q R : Prop
h : P â†’ Q â†’ R
h2 : Â¬R
h3 : P
h4 : Q
âŠ¢ R
```
:::
:::

As before, we can now prove `R` by combining `h`, `h3`, and `h4`.  In fact, we could do it in one step: by modus ponens, `h h3` is a proof of `Q â†’ R`, and therefore, by another application of modus ponens, `(h h3) h4` is a proof of `R`.  The parentheses here are not necessary; Lean will interpret `h h3 h4` as `(h h3) h4`, so we can complete the proof like this:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_2_4_v3 (P Q R : Prop)
    (h : P â†’ (Q â†’ R)) : Â¬R â†’ (P â†’ Â¬Q) := by
  assume h2 : Â¬R
  assume h3 : P
  by_contra h4
  contradict h2
  show R from h h3 h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

You could shorten this proof slightly by replacing the lines `by_contra h4` and `contradict h2` with the single line `contradict h2 with h4`.

There is one more idea that is introduced in Section 3.2 of *HTPI*.  The last example in that section illustrates how you can sometimes use rules of inference to work backwards.  Here's a similar example in Lean:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_2_5
    (U : Type) (A B C : Set U) (a : U)
    (h1 : a âˆˆ A) (h2 : a âˆ‰ A \ B)
    (h3 : a âˆˆ B â†’ a âˆˆ C) : a âˆˆ C := by

  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
a : U
h1 : a âˆˆ A
h2 : Â¬a âˆˆ A \ B
h3 : a âˆˆ B â†’ a âˆˆ C
âŠ¢ a âˆˆ C
```
:::
:::

The goal is `a âˆˆ C`, and the only given that even mentions `C` is `h3 : a âˆˆ B â†’ a âˆˆ C`.  If only we could prove `a âˆˆ B`, then we could apply `h3`, using modus ponens, to reach our goal.  So it would make sense to work toward the goal of proving `a âˆˆ B`.

To get Lean to use this proof strategy, we use the tactic `apply h3 _`.  The underscore here represents a blank to be filled in by Lean.  You might think of this tactic as asking Lean the question: If we want `h3 _` to be a proof of the goal `a âˆˆ C`, what do we have to put in the blank?  Lean is able to figure out that the answer is: a proof of `a âˆˆ B`.  So it sets the goal to be `a âˆˆ B`, since a proof of that goal, when inserted into the blank in `h3 _`, would prove the original goal `a âˆˆ C`:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_2_5
    (U : Type) (A B C : Set U) (a : U)
    (h1 : a âˆˆ A) (h2 : a âˆ‰ A \ B)
    (h3 : a âˆˆ B â†’ a âˆˆ C) : a âˆˆ C := by
  apply h3 _
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C: Set U
a : U
h1 : a âˆˆ A
h2 : Â¬a âˆˆ A \ B
h3 : a âˆˆ B â†’ a âˆˆ C
âŠ¢ a âˆˆ B
```
:::
:::

It may not be clear what to do next, but the given `h2` is a negative statement, so perhaps reexpressing it will help.  Writing out the definition of set difference, `h2` means `Â¬(a âˆˆ A âˆ§ a âˆ‰ B)`, and then one of De Morgan's laws and a conditional law allow us to rewrite it first as `a âˆ‰ A âˆ¨ a âˆˆ B` and then as `a âˆˆ A â†’ a âˆˆ B`.  Of course, we have tactics to accomplish all of these reexpressions:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_2_5
    (U : Type) (A B C : Set U) (a : U)
    (h1 : a âˆˆ A) (h2 : a âˆ‰ A \ B)
    (h3 : a âˆˆ B â†’ a âˆˆ C) : a âˆˆ C := by
  apply h3 _
  define at h2
  demorgan at h2; conditional at h2
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
a : U
h1 : a âˆˆ A
h2 : a âˆˆ A â†’ a âˆˆ B
h3 : a âˆˆ B â†’ a âˆˆ C
âŠ¢ a âˆˆ B
```
:::
:::

And now it is easy to complete the proof by applying modus ponens, using `h2` and `h1`:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_2_5
    (U : Type) (A B C : Set U) (a : U)
    (h1 : a âˆˆ A) (h2 : a âˆ‰ A \ B)
    (h3 : a âˆˆ B â†’ a âˆˆ C) : a âˆˆ C := by
  apply h3 _
  define at h2
  demorgan at h2; conditional at h2
  show a âˆˆ B from h2 h1
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

We will see many more uses of the `apply` tactic later in this book.

Sections 3.1 and 3.2 of *HTPI* contain several proofs that involve algebraic reasoning.  Although one can do such proofs in Lean, it requires ideas that we are not ready to introduce yet.  So for the moment we will stick to proofs involving only logic and set theory.

### Exercises

Fill in proofs of the following theorems.  All exercises are taken from *HTPI*.

::: {.numex arguments="1"}
```lean
theorem Exercise_3_2_1a (P Q R : Prop)
    (h1 : P â†’ Q) (h2 : Q â†’ R) : P â†’ R := by
  
  **done::
```
:::

::: {.numex arguments="2"}
```lean
theorem Exercise_3_2_1b (P Q R : Prop)
    (h1 : Â¬R â†’ (P â†’ Â¬Q)) : P â†’ (Q â†’ R) := by
  
  **done::
```
:::

::: {.numex arguments="3"}
```lean
theorem Exercise_3_2_2a (P Q R : Prop)
    (h1 : P â†’ Q) (h2 : R â†’ Â¬Q) : P â†’ Â¬R := by
  
  **done::
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_2_2b (P Q : Prop)
    (h1 : P) : Q â†’ Â¬(Q â†’ Â¬P) := by
  
  **done::
```
:::

## 3.3. Proofs Involving Quantifiers

In the notation used in *HTPI*, if $P(x)$ is a statement about $x$, then $\forall x\, P(x)$ means "for all $x$, $P(x)$," and $\exists x\, P(x)$ means "there exists at least one $x$ such that $P(x)$."  The letter $P$ here does not stand for a proposition; it is only when it is applied to some object $x$ that we get a proposition.  We will say that $P$ is a *predicate*, and when we apply $P$ to an object $x$ we get the proposition $P(x)$.  You might want to think of the predicate $P$ as representing some property that an object might have, and the proposition $P(x)$ asserts that $x$ has that property.

To use a predicate in Lean, you must tell Lean the type of objects to which it applies.  If `U` is a type, then `Pred U` is the type of predicates that apply to objects of type `U`.  If `P` has type `Pred U` (that is, `P` is a predicate applying to objects of type `U`) and `x` has type `U`, then to apply `P` to `x` we just write `P x` (with a space but no parentheses).  Thus, if we have `P : Pred U` and `x : U`, then `P x` is an expression of type `Prop`.  That is, `P x` is a proposition, and its meaning is that `x` has the property represented by the predicate `P`.

There are a few differences between the way quantified statements are written in *HTPI* and the way they are written in Lean.  First of all, when we apply a quantifier to a variable in Lean we will specify the type of the variable explicitly.  Also, Lean requires that after specifying the variable and its type, you must put a comma before the proposition to which the quantifier is applied.  Thus, if `P` has type `Pred U`, then to say that `P` holds for all objects of type `U` we would write `âˆ€ (x : U), P x`.  Similarly, `âˆƒ (x : U), P x` is the proposition asserting that there exists at least one `x` of type `U` such that `P x`.

And there is one more important difference between the way quantified statements are written in *HTPI* and Lean.  In *HTPI*, a quantifier is interpreted as applying to as little as possible.  Thus, $\forall x\, P(x) \wedge Q(x)$ is interpreted as $(\forall x\, P(x)) \wedge Q(x)$; if you want the quantifier $\forall x$ to apply to the entire statement $P(x) \wedge Q(x)$ you must use parentheses and write $\forall x(P(x) \wedge Q(x))$.  The convention in Lean is exactly the opposite:  a quantifier applies to as much as possible.  Thus, Lean will interpret `âˆ€ (x : U), P x âˆ§ Q x` as meaning `âˆ€ (x : U), (P x âˆ§ Q x)`.  If you want the quantifier to apply to only `P x`, then you must use parentheses and write `(âˆ€ (x : U), P x) âˆ§ Q x`.

With this preparation, we are ready to consider how to write proofs involving quantifiers in Lean.  The most common way to prove a goal of the form `âˆ€ (x : U), P x` is to use the following strategy:

#### To prove a goal of the form `âˆ€ (x : U), P x`:

::: {.ind}
Let `x` stand for an arbitrary object of type `U` and prove `P x`.  If the letter `x` is already being used in the proof to stand for something, then you must choose an unused variable, say `y`, to stand for the arbitrary object, and prove `P y`.
:::

To do this in Lean, you should use the tactic `fix x : U`, which tells Lean to treat `x` as standing for some fixed but arbitrary object of type `U`.  This has the following effect on the tactic state:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
âŠ¢ âˆ€ (x : U), P x
```
:::

::: {.aft}
```state
>> â‹®
x : U
âŠ¢ P x
```
:::
:::

To use a given of the form `âˆ€ (x : U), P x`, we usually apply a rule of inference called *universal instantiation*, which is described by the following proof strategy:

#### To use a given of the form `âˆ€ (x : U), P x`:

::: {.ind}
You may plug in any value of type `U`, say `a`, for `x` and use this given to conclude that `P a` is true.
:::

This strategy says that if you have `h : âˆ€ (x : U), P x` and `a : U`, then you can infer `P a`.  Indeed, in this situation Lean will recognize `h a` as a proof of `P a`.  For example, you can write `have h' : P a := h a` in a Lean tactic-mode proof, and Lean will add `h' : P a` to the tactic state.

Let's try these strategies out in a Lean proof.  In Lean, if you don't want to give a theorem a name, you can simply call it an `example` rather than a `theorem`, and then there is no need to give it a name.  In the following theorem, you can enter the symbol `âˆ€` by typing `\forall` or `\all`, and you can enter `âˆƒ` by typing `\exists` or `\ex`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†’ Â¬Q x)
    (h2 : âˆ€ (x : U), Q x) :
    Â¬âˆƒ (x : U), P x := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†’ Â¬Q x
h2 : âˆ€ (x : U), Q x
âŠ¢ Â¬âˆƒ (x : U), P x
```
:::
:::

<!-- With pp.funBinderTypes, don't need this comment anymore
(In the tactic state, why doesn't Lean show the type of the variable `x` after the existential quantifier in the goal?  I don't know.  Sometimes you can leave out the type of a quantified variable and Lean is able to figure it out on its own.  But sometimes Lean is unable to figure out the type if it is not supplied, and you will get an error message if you leave it out.  To avoid confusion, we will always include the type of the quantified variable when we enter a quantified statement into Lean, but you will notice that Lean generally leaves out the type when it displays existentially quantified statements in the tactic state.)
-->

To use the givens `h1` and `h2`, we will probably want to use universal instantiation.  But to do that we would need an object of type `U` to plug in for `x` in `h1` and `h2`, and there is no object of type `U` in the tactic state.  So at this point, we can't apply universal instantiation to `h1` and `h2`.  We should watch for an object of type `U` to come up in the course of the proof, and consider applying universal instantiation if one does.  Until then, we turn our attention to the goal.

The goal is a negative statement, so we begin by reexpressing it as an equivalent positive statement, using a quantifier negation law.  The tactic `quant_neg` applies a quantifier negation law to rewrite the goal.  As with the other tactics for applying logical equivalences, you can write `quant_neg at h` if you want to apply a quantifier negation law to a given `h`.  The effect of the tactic can be summarized as follows:

::: {style="margin: 0% 10%"}
| | `quant_neg` Tactic | |
|:--:|:--:|:--:|
| `Â¬âˆ€ (x : U), P x` | is changed to | `âˆƒ (x : U), Â¬P x` |
| `Â¬âˆƒ (x : U), P x` | is changed to | `âˆ€ (x : U), Â¬P x` |
| `âˆ€ (x : U), P x` | is changed to | `Â¬âˆƒ (x : U), Â¬P x` |
| `âˆƒ (x : U), P x` | is changed to | `Â¬âˆ€ (x : U), Â¬P x` |
:::

Using the `quant_neg` tactic leads to the following result.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†’ Â¬Q x)
    (h2 : âˆ€ (x : U), Q x) :
    Â¬âˆƒ (x : U), P x := by
  quant_neg     --Goal is now âˆ€ (x : U), Â¬P x
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†’ Â¬Q x
h2 : âˆ€ (x : U), Q x
âŠ¢ âˆ€ (x : U), Â¬P x
```
:::
:::

Now the goal starts with `âˆ€`, so we use the strategy above and introduce an arbitrary object of type `U`.  Since the variable `x` occurs as a bound variable in several statements in this theorem, it might be best to use a different letter for the arbitrary object; this isn't absolutely necessary, but it may help to avoid confusion.  So our next tactic is `fix y : U`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†’ Â¬Q x)
    (h2 : âˆ€ (x : U), Q x) :
    Â¬âˆƒ (x : U), P x := by
  quant_neg     --Goal is now âˆ€ (x : U), Â¬P x
  fix y : U
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†’ Â¬Q x
h2 : âˆ€ (x : U), Q x
y : U
âŠ¢ Â¬P y
```
:::
:::

Now we have an object of type `U` in the tactic state, namely, `y`.  So let's try applying universal instantiation to `h1` and `h2` and see if it helps.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†’ Â¬Q x)
    (h2 : âˆ€ (x : U), Q x) :
    Â¬âˆƒ (x : U), P x := by
  quant_neg     --Goal is now âˆ€ (x : U), Â¬P x
  fix y : U
  have h3 : P y â†’ Â¬Q y := h1 y
  have h4 : Q y := h2 y
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†’ Â¬Q x
h2 : âˆ€ (x : U), Q x
y : U
h3 : P y â†’ Â¬Q y
h4 : Q y
âŠ¢ Â¬P y
```
:::
:::

We're almost done, because the goal now follows easily from `h3` and `h4`.  If we use the contrapositive law to rewrite `h3` as `Q y â†’ Â¬P y`, then we can apply modus ponens to the rewritten `h3` and `h4` to reach the goal:

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†’ Â¬Q x)
    (h2 : âˆ€ (x : U), Q x) :
    Â¬âˆƒ (x : U), P x := by
  quant_neg     --Goal is now âˆ€ (x : U), Â¬P x
  fix y : U
  have h3 : P y â†’ Â¬Q y := h1 y
  have h4 : Q y := h2 y
  contrapos at h3  --Now h3 : Q y â†’ Â¬P y
  show Â¬P y from h3 h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

Our next example is a theorem of set theory.  You already know how to type a few set theory symbols in Lean, but you'll need a few more for our next example.  Here's a summary of the most important set theory symbols and how to type them in Lean.

::: {style="margin: 0% 10%"}
| Symbol | How To Type It |
|:----:|:-------:|
| `âˆˆ` | `\in` |
| `âˆ‰` | `\notin` or `\inn` |
| `âŠ†` | `\sub` |
| `âŠˆ` | `\subn` |
| `=` | `=` |
| `â‰ ` | `\ne` |
| `âˆª` | `\union` or `\cup` |
| `âˆ©` | `\inter` or `\cap` |
| `\` | `\\` |
| `â–³` | `\bigtriangleup` |
| `âˆ…` | `\emptyset` |
| `ð’«` | `\powerset` |
:::

With this preparation, we can turn to our next example.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
âŠ¢ A âŠ† C
```
:::
:::

We begin by using the `define` tactic to write out the definition of the goal.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C: Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
âŠ¢ âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ A â†’ a âˆˆ C
```
:::
:::

Notice that Lean's definition of the goal starts with `âˆ€ â¦ƒa : Uâ¦„`, not `âˆ€ (a : U)`.  Why did Lean use those funny double braces rather than parentheses?  We'll return to that question shortly.  The difference doesn't affect our next steps, which are to introduce an arbitrary object `y` of type `U` and assume `y âˆˆ A`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
y : U
h3 : y âˆˆ A
âŠ¢ y âˆˆ C
```
:::
:::

Now we can combine `h2` and `h3` to conclude that `Â¬y âˆˆ B`.  Since we have `y : U`, by universal instantiation, `h2 y` is a proof of `y âˆˆ A â†’ Â¬y âˆˆ B`, and therefore by modus ponens, `h2 y h3` is a proof of `Â¬y âˆˆ B`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  have h4 : y âˆ‰ B := h2 y h3
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
y : U
h3 : y âˆˆ A
h4 : Â¬y âˆˆ B
âŠ¢ y âˆˆ C
```
:::
:::

We should be able to use similar reasoning to combine `h1` and `h3`, if we first write out the definition of `h1`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  have h4 : y âˆ‰ B := h2 y h3
  define at h1  --h1 : âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B âˆª C
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ A â†’ a âˆˆ B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
y : U
h3 : y âˆˆ A
h4 : Â¬y âˆˆ B
âŠ¢ y âˆˆ C
```
:::
:::

Once again, Lean has used double braces to define `h1`, and now we are ready to explain what they mean.  If the definition had been `h1 : âˆ€ (a : U), a âˆˆ A â†’ a âˆˆ B âˆª C`, then exactly as in the previous step, `h1 y h3` would be a proof of `y âˆˆ B âˆª C`.  The use of double braces in the definition `h1 : âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B âˆª C` means that you don't need to tell Lean that `y` is being plugged in for `a` in the universal instantiation step; Lean will figure that out on its own.  Thus, you can just write `h1 h3` as a proof of `y âˆˆ B âˆª C`.  Indeed, if you write `h1 y h3` then you will get an error message, because Lean expects *not* to be told what to plug in for `a`.  You might think of the definition of `h1` as meaning `h1 : _ âˆˆ A â†’ _ âˆˆ B âˆª C`, where the blanks can be filled in with anything of type `U` (with the same thing being put in both blanks).  When you ask Lean to apply modus ponens by combining this statement with `h3 : y âˆˆ A`, Lean figures out that in order for modus ponens to apply, the blanks must be filled in with `y`.

In this situation, the `a` in `h1` is called an *implicit argument*.  What this means is that, when `h1` is applied to make an inference in a proof, the value to be assigned to `a` is not specified explicitly; rather, the value is inferred by Lean.  We will see many more examples of implicit arguments later in this book.  In fact, there are two slightly different kinds of implicit arguments in Lean.  One kind is indicated using the double braces `â¦ƒ â¦„` used in this example, and the other is indicated using curly braces, `{ }`.  The difference between these two kinds of implicit arguments won't be important in this book; all that will matter to us is that if you see either `âˆ€ â¦ƒa : Uâ¦„` or `âˆ€ {a : U}` rather than `âˆ€ (a : U)`, then you must remember that `a` is an implicit argument.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  have h4 : y âˆ‰ B := h2 y h3
  define at h1  --h1 : âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B âˆª C
  have h5 : y âˆˆ B âˆª C := h1 h3
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ A â†’ a âˆˆ B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
y : U
h3 : y âˆˆ A
h4 : Â¬y âˆˆ B
h5 : y âˆˆ B âˆª C
âŠ¢ y âˆˆ C
```
:::
:::


If Lean was able to figure out that `y` should be plugged in for `a` in `h1` in this step, couldn't it have figured out that `y` should be plugged in for `x` in `h2` in the previous `have` step?  The answer is yes.  Of course, in `h2`, `x` was not an implicit argument, so Lean wouldn't *automatically* figure out what to plug in for `x`.  But we could have asked it to figure it out by writing the proof in the previous step as `h2 _ h3` rather than `h2 y h3`.  In a term-mode proof, an underscore represents a blank to be filled in by Lean.  Try changing the earlier step of the proof to `have h4 : y âˆ‰ B := h2 _ h3` and you will see that Lean will accept it.  Of course, in this case this doesn't save us any typing, but in some situations it is useful to let Lean figure out some part of a proof.

Lean's ability to fill in blanks in term-mode proofs is limited.  For example, if you try changing the previous step to `have h4 : y âˆ‰ B := h2 y _`, you'll get a red squiggle under the blank, and the error message in the Infoview pane will say `don't know how to synthesize placeholder`.  In other words, Lean was unable to figure out how to fill in the blank in this case.  In future proofs you might try replacing some expressions with blanks to get a feel for what Lean can and cannot figure out for itself.

Continuing with the proof, we see that we're almost done, because we can combine `h4` and `h5` to reach our goal.  To see how, we first write out the definition of `h5`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  have h4 : y âˆ‰ B := h2 y h3
  define at h1  --h1 : âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B âˆª C
  have h5 : y âˆˆ B âˆª C := h1 h3
  define at h5  --h5 : y âˆˆ B âˆ¨ y âˆˆ C
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ A â†’ a âˆˆ B âˆª C
h2 : âˆ€ (x : U),
>>  x âˆˆ A â†’ Â¬x âˆˆ B
y : U
h3 : y âˆˆ A
h4 : Â¬y âˆˆ B
h5 : y âˆˆ B âˆ¨ y âˆˆ C
âŠ¢ y âˆˆ C
```
:::
:::

A conditional law will convert `h5` to `Â¬y âˆˆ B â†’ y âˆˆ C`, and then modus ponens with `h4` will complete the proof.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : âˆ€ (x : U), x âˆˆ A â†’ x âˆ‰ B) : A âŠ† C := by
  define  --Goal: âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ C
  fix y : U
  assume h3 : y âˆˆ A
  have h4 : y âˆ‰ B := h2 y h3
  define at h1  --h1 : âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B âˆª C
  have h5 : y âˆˆ B âˆª C := h1 h3
  define at h5  --h5 : y âˆˆ B âˆ¨ y âˆˆ C
  conditional at h5  --h5 : Â¬y âˆˆ B â†’ y âˆˆ C
  show y âˆˆ C from h5 h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

Next we turn to strategies for working with existential quantifiers.

#### To prove a goal of the form `âˆƒ (x : U), P x`:

::: {.ind}
Find a value of `x`, say `a`, for which you think `P a` is true, and prove `P a`.
:::

This strategy is based on the fact that if you have `a : U` and `h : P a`, then you can infer `âˆƒ (x : U), P x`.  Indeed, in this situation the expression `Exists.intro a h` is a Lean term-mode proof of `âˆƒ (x : U), P x`.  The name `Exists.intro` indicates that this is a rule for introducing an existential quantifier.

As suggested by the strategy above, we will often want to use this rule in situations in which our goal is `âˆƒ (x : U), P x` and we have an object `a` of type `U` that we think makes `P a` true, but we don't yet have a proof of `P a`.  In that situation we can use the tactic `apply Exists.intro a _`.  Recall that the `apply` tactic asks Lean to figure out what to put in the blank to turn `Exists.intro a _` into a proof of the goal.  Lean will figure out that what needs to go in the blank is a proof of `P a`, so it sets `P a` to be the goal.  In other words, the tactic `apply Exists.intro a _` has the following effect on the tactic state:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
a : U
âŠ¢ âˆƒ (x : U), P x
```
:::

::: {.aft}
```state
>> â‹®
a : U
âŠ¢ P a
```
:::
:::

Our strategy for using an existential given is a rule that is called *existential instantiation* in *HTPI*:

#### To use a given of the form `âˆƒ (x : U), P x`:

::: {.ind}
Introduce a new variable, say `a`, into the proof to stand for an object of type `U` for which `P a` is true.
:::

Suppose that, in a Lean proof, you have `h : âˆƒ (x : U), P x`.  To apply the existential instantiation rule, you would use the tactic `obtain (a : U) (h' : P a) from h`.  This tactic introduces into the tactic state both a new variable `a` of type `U` and also the identifier `h'` for the new given `P a`.  Note that `h` can be any proof of a statement of the form `âˆƒ (x : U), P x`; it need not be just a single identifier.

Often, if your goal is an existential statement `âˆƒ (x : U), P x`, you won't be able to use the strategy above for existential goals right away, because you won't know what object `a` to use in the tactic `apply Exists.intro a _`.  You may have to wait until a likely candidate for `a` pops up in the course of the proof.  On the other hand, it is usually best to use the `obtain` tactic right away if you have an existential given.  This is illustrated in our next example.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
âŠ¢ âˆƒ (x : U), Â¬P x
```
:::
:::

The goal is the existential statement `âˆƒ (x : U), Â¬P x`, and our strategy for existential goals says that we should try to find an object `a` of type `U` that we think would make the statement `Â¬P a` true.  But we don't have any objects of type `U` in the tactic state, so it looks like we can't use that strategy yet.  Similarly, we can't use the given `h1` yet, since we have nothing to plug in for `x` in `h1`.  However, `h2` is an existential given, and we can use it right away.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
âŠ¢ âˆƒ (x : U), Â¬P x
```
:::
:::

Now that we have `a : U`, we can apply universal instantiation to `h1`, plugging in `a` for `x`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
h4 : âˆƒ (y : U), P a â†’ Â¬Q y
âŠ¢ âˆƒ (x : U), Â¬P x
```
:::
:::

By the way, this is another case in which Lean could have figured out a part of the proof on its own.  Try changing `h1 a` in the last step to `h1 _`, and you'll see that Lean will be able to figure out how to fill in the blank.

Our new given `h4` is another existential statement, so again we use it right away to introduce another object of type `U`.  Since this object might not be the same as `a`, we must give it a different name.  (Indeed, if you try to use the name `a` again, Lean will give you an error message.)

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  obtain (b : U) (h5 : P a â†’ Â¬ Q b) from h4
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
h4 : âˆƒ (y : U), P a â†’ Â¬Q y
b : U
h5 : P a â†’ Â¬Q b
âŠ¢ âˆƒ (x : U), Â¬P x
```
:::
:::

We have not yet used `h3`.  We could plug in either `a` or `b` for `y` in `h3`, but a little thought should show you that plugging in `b` is more useful.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  obtain (b : U) (h5 : P a â†’ Â¬ Q b) from h4
  have h6 : P a â†’ Q b := h3 b
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
h4 : âˆƒ (y : U), P a â†’ Â¬Q y
b : U
h5 : P a â†’ Â¬Q b
h6 : P a â†’ Q b
âŠ¢ âˆƒ (x : U), Â¬P x
```
:::
:::

Now look at `h5` and `h6`.  They show that `P a` leads to contradictory conclusions, `Â¬Q b` and `Q b`.  This means that `P a` must be false.  We finally know what value of `x` to use to prove the goal.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  obtain (b : U) (h5 : P a â†’ Â¬ Q b) from h4
  have h6 : P a â†’ Q b := h3 b
  apply Exists.intro a _
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
h4 : âˆƒ (y : U), P a â†’ Â¬Q y
b : U
h5 : P a â†’ Â¬Q b
h6 : P a â†’ Q b
âŠ¢ Â¬P a
```
:::
:::

Since the goal is now a negative statement that cannot be reexpressed as a positive statement, we use proof by contradiction.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  obtain (b : U) (h5 : P a â†’ Â¬ Q b) from h4
  have h6 : P a â†’ Q b := h3 b
  apply Exists.intro a _
  by_contra h7
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), âˆƒ (y : U),
>>  P x â†’ Â¬Q y
h2 : âˆƒ (x : U), âˆ€ (y : U),
>>  P x â†’ Q y
a : U
h3 : âˆ€ (y : U), P a â†’ Q y
h4 : âˆƒ (y : U), P a â†’ Â¬Q y
b : U
h5 : P a â†’ Â¬Q b
h6 : P a â†’ Q b
h7 : P a
âŠ¢ False
```
:::
:::

Now `h5 h7` is a proof of `Â¬Q b` and `h6 h7` is a proof of `Q b`, so `h5 h7 (h6 h7)` is a proof of `False`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), âˆƒ (y : U), P x â†’ Â¬ Q y)
    (h2 : âˆƒ (x : U), âˆ€ (y : U), P x â†’ Q y) :
    âˆƒ (x : U), Â¬P x := by
  obtain (a : U)
    (h3 : âˆ€ (y : U), P a â†’ Q y) from h2
  have h4 : âˆƒ (y : U), P a â†’ Â¬ Q y := h1 a
  obtain (b : U) (h5 : P a â†’ Â¬ Q b) from h4
  have h6 : P a â†’ Q b := h3 b
  apply Exists.intro a _
  by_contra h7
  show False from h5 h7 (h6 h7)
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

We conclude this section with the theorem from Example 3.3.5 in *HTPI*.  That theorem concerns a union of a family of sets.  In *HTPI*, such a union is written using a large union symbol, $\bigcup$.  Lean uses the symbol `â‹ƒâ‚€`, which is entered by typing `\U0` (that is, backslash--capital U--zero).  For an intersection of a family of sets, Lean uses `â‹‚â‚€`, typed as `\I0`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
âŠ¢ â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B
```
:::
:::

Note that `F` has type `Set (Set U)`, which means that it is a set whose elements are sets of objects of type `U`.  Since the goal is a conditional statement, we assume the antecedent and set the consequent as our goal.  We'll also write out the definition of the new goal.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : â‹ƒâ‚€F âŠ† B
âŠ¢ âˆ€ â¦ƒa : Set Uâ¦„,
>>  a âˆˆ F â†’ a âˆˆ ð’« B
```
:::
:::

Based on the form of the goal, we introduce an arbitrary object `x` of type `Set U` and assume `x âˆˆ F`.  The new goal will be `x âˆˆ ð’« B`.  The `define` tactic works out that this means `x âŠ† B`, which can be further expanded to `âˆ€ â¦ƒa : Uâ¦„, a âˆˆ x â†’ a âˆˆ B`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : â‹ƒâ‚€F âŠ† B
x : Set U
h2 : x âˆˆ F
âŠ¢ âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ x â†’ a âˆˆ B
```
:::
:::

Once again the form of the goal dictates our next steps: introduce an arbitrary `y` of type `U` and assume `y âˆˆ x`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : â‹ƒâ‚€F âŠ† B
x : Set U
h2 : x âˆˆ F
y : U
h3 : y âˆˆ x
âŠ¢ y âˆˆ B
```
:::
:::

The goal can be analyzed no further, so we turn to the givens.  We haven't used `h1` yet.  To see how to use it, we write out its definition.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  define at h1
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ â‹ƒâ‚€F â†’ a âˆˆ B
x : Set U
h2 : x âˆˆ F
y : U
h3 : y âˆˆ x
âŠ¢ y âˆˆ B
```
:::
:::

Now we see that we can try to use `h1` to reach our goal.  Indeed, `h1 _` would be a proof of the goal if we could fill in the blank with a proof of `y âˆˆ âˆªâ‚€F`.  So we use the `apply h1 _` tactic.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  define at h1
  apply h1 _
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ â‹ƒâ‚€F â†’ a âˆˆ B
x : Set U
h2 : x âˆˆ F
y : U
h3 : y âˆˆ x
âŠ¢ y âˆˆ â‹ƒâ‚€F
```
:::
:::

Once again we have a goal that can be analyzed by using the `define` tactic.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  define at h1
  apply h1 _
  define
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ â‹ƒâ‚€F â†’ a âˆˆ B
x : Set U
h2 : x âˆˆ F
y : U
h3 : y âˆˆ x
âŠ¢ âˆƒ (t : Set U),
>>  t âˆˆ F âˆ§ y âˆˆ t
```
:::
:::

Our goal is now an existential statement, so we look for a value of `t` that will make the statement `t âˆˆ F âˆ§ y âˆˆ t` true.  The givens `h2` and `h3` tell us that `x` is such a value, so as described earlier our next tactic should be `apply Exists.intro x _`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  define at h1
  apply h1 _
  define
  apply Exists.intro x _
  **done::
```
:::

::: {.outpt}
```state
U : Type
B : Set U
F : Set (Set U)
h1 : âˆ€ â¦ƒa : Uâ¦„,
>>  a âˆˆ â‹ƒâ‚€F â†’ a âˆˆ B
x : Set U
h2 : x âˆˆ F
y : U
h3 : y âˆˆ x
âŠ¢ x âˆˆ F âˆ§ y âˆˆ x
```
:::
:::

Clearly the goal now follows from `h2` and `h3`, but how do we write the proof in Lean?  Since we need to introduce the "and" symbol `âˆ§`, you shouldn't be surprised to learn that the rule we need is called `And.intro`.  Proof strategies for statements involving "and" will be the subject of the next section.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_3_5 (U : Type) (B : Set U)
    (F : Set (Set U)) : â‹ƒâ‚€F âŠ† B â†’ F âŠ† ð’« B := by
  assume h1 : â‹ƒâ‚€F âŠ† B
  define
  fix x : Set U
  assume h2 : x âˆˆ F
  define
  fix y : U
  assume h3 : y âˆˆ x
  define at h1
  apply h1 _
  define
  apply Exists.intro x _
  show x âˆˆ F âˆ§ y âˆˆ x from And.intro h2 h3
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

You might want to compare the Lean proof above to the way the proof was written in *HTPI*.  Here are the theorem and proof from *HTPI*:

::: {.thm}
Suppose $B$ is a set and $\mathcal{F}$ is a family of sets.  If $\bigcup\mathcal{F} \subseteq B$ then $\mathcal{F} \subseteq \mathscr{P}(B)$.
:::
::: {.proof}
Suppose $\bigcup \mathcal{F} \subseteq B$.  Let $x$ be an arbitrary element of $\mathcal{F}$.  Let $y$ be an arbitrary element of $x$.  Since $y \in x$ and $x \in \mathcal{F}$, by the definition of $\bigcup \mathcal{F}$, $y \in \bigcup \mathcal{F}$.  But then since $\bigcup \mathcal{F} \subseteq B$, $y \in B$.  Since $y$ was an arbitrary element of $x$, we can conclude that $x \subseteq B$, so $x \in \mathscr{P}(B)$.  But $x$ was an arbitrary element of $\mathcal{F}$, so this shows that $\mathcal{F} \subseteq \mathscr{P}(B)$, as required. [&nbsp;â–¡]{.excl}\qedhere
:::

### Exercises

::: {.numex arguments="1"}
```lean
theorem Exercise_3_3_1
    (U : Type) (P Q : Pred U) (h1 : âˆƒ (x : U), P x â†’ Q x) :
    (âˆ€ (x : U), P x) â†’ âˆƒ (x : U), Q x := by
  
  **done::
```
:::

::: {.numex arguments="2"}
```lean
theorem Exercise_3_3_8 (U : Type) (F : Set (Set U)) (A : Set U)
    (h1 : A âˆˆ F) : A âŠ† â‹ƒâ‚€F := by
  
  **done::
```
:::

::: {.numex arguments="3"}
```lean
theorem Exercise_3_3_9 (U : Type) (F : Set (Set U)) (A : Set U)
    (h1 : A âˆˆ F) : â‹‚â‚€F âŠ† A := by
  
  **done::
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_3_10 (U : Type) (B : Set U) (F : Set (Set U))
    (h1 : âˆ€ (A : Set U), A âˆˆ F â†’ B âŠ† A) : B âŠ† â‹‚â‚€F := by
  
  **done::
```
:::

::: {.numex arguments="5"}
```lean
theorem Exercise_3_3_13 (U : Type)
    (F G : Set (Set U)) : F âŠ† G â†’ â‹‚â‚€G âŠ† â‹‚â‚€F := by
  
  **done::
```
:::

## 3.4. Proofs Involving Conjunctions and Biconditionals

The strategies in *HTPI* for working with conjunctions are very simple.

#### To prove a goal of the form `P âˆ§ Q`:

::: {.ind}
Prove `P` and `Q` separately.
:::

We already saw an example, at the end of the last section, of the use of the rule `And.intro` to prove a conjunction.  In general, if you have `h1 : P` and `h2 : Q`, then `And.intro h1 h2` is a proof of `P âˆ§ Q`.  It follows that if your goal is `P âˆ§ Q` but you don't yet have proofs of `P` and `Q`, then you can use the tactic `apply And.intro _ _`.  Lean will figure out that the blanks need to be filled in with proofs of `P` and `Q`, so it will ask you to prove `P` and `Q` separately, as suggested by the strategy above.

If you already have a proof of either `P` or `Q`, then you can fill in one of the blanks in the `apply` tactic.  For example, if you have `h : P`, then you can write `apply And.intro h _`, and Lean will tell you that you just have to prove `Q` to complete the proof.  Similarly, if you have `h : Q`, then `apply And.intro _ h` will lead to just the single goal `P`.  There is also a shortcut you can use with the `apply` tactic: any blanks that come at the end of the tactic can be left out.  So instead of `apply And.intro _ _`, you can just write `apply And.intro`, and instead of `apply And.intro h _`, you can write `apply And.intro h`.  On the other hand, `apply And.intro _ h` can't be shortened; it is only blanks *at the end* that can be left out.

The strategy for a given that is a conjunction is similar.

#### To use a given of the form `P âˆ§ Q`:

::: {.ind}
Treat this as two separate givens: `P`, and `Q`.
:::

If you have a given `h : P âˆ§ Q`, then Lean will recognize `h.left` as a proof of `P`, and `h.right` as a proof of `Q`.

Here's an example that illustrates these strategies.  It is similar to Example 3.4.1 in *HTPI*

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
âŠ¢ A âˆ© C âŠ† B \ D
```
:::
:::

The `define` tactic will rewrite the goal as `âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A âˆ© C â†’ a âˆˆ B \ D`, and then we can introduce an arbitrary `x : U` and assume `x âˆˆ A âˆ© C`.  

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ© C
âŠ¢ x âˆˆ B \ D
```
:::
:::

Now let's take a look at the definitions of `h3` and the goal:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
âŠ¢ x âˆˆ B âˆ§ Â¬x âˆˆ D
```
:::
:::

Since the goal is now a conjuction, we apply the strategy above by using the tactic `apply And.intro`.

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  **done::
```
:::

::: {.outpt}
```state
case left
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
âŠ¢ x âˆˆ B
case right
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
âŠ¢ Â¬x âˆˆ D
```
:::
:::

Look carefully at the tactic state.  Lean has listed *two* goals, one after the other, and it has helpfully labeled them "case left" and "case right," indicating that the first goal is to prove the left side of the conjunction and the second is to prove the right.  The given information in both cases is the same, but in the first case the goal is `x âˆˆ B`, and in the second it is `Â¬x âˆˆ D`.  At this point, if we simply continue with the proof, Lean will interpret out tactics as applying to the first goal, until we achieve that goal.  Once we achieve it, Lean will move on to the second goal.

However, we can make our proof more readable by separating and labeling the proofs of the two goals.  To do this, we type a bullet (which looks like this: `Â·`) and then a comment describing the first goal.  (To type a bullet, type `\.`---that is, backslash--period.)  The proof of the first goal will appear below this line, indented further and ending with `done`.  To prepare for this, we leave a blank line, type tab to increase the indenting, and then type `done`.  Then we do the same for the second goal:  On the next line, we return to the previous level of indenting and type a bullet and a comment describing the second goal.  We follow this with a blank line and then an indented `done` to indicate the end of the proof of the second goal.  We're going to work on the first goal first, so we click on the first blank line to position the cursor there.  The screen now looks like this:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  Â· -- Proof that x âˆˆ B

    **done::
  Â· -- Proof that Â¬x âˆˆ D

    **done::
  done
```
:::

::: {.outpt}
```state
case left
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
âŠ¢ x âˆˆ B
```
:::
:::

Of course, there are red squiggles under both new occurrences of `done`, since neither goal has yet been achieved.  We can work on the goals in either order by positioning the cursor on either blank line, and the Infoview pane will show the tactic state for the goal at the position of the cursor.  In the display above, we have positioned the cursor on the first blank line, so the Infoview shows the tactic state for the first goal.

This first goal is easy:  We have `h1 : A âŠ† B` and, as explained above, `h3.left : x âˆˆ A`.  As we have seen in several previous examples, the tactic `define at h1` will rewrite `h1` as `âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A â†’ a âˆˆ B`, and then `h1 h3.left` will be a proof of `x âˆˆ B`.  And now we'll let you in on a little secret: usually the `define` tactic isn't really necessary.  *You* may find the `define` tactic to be useful in many situations, because it helps you see what a statement means.  But *Lean* doesn't need to be told to work out what the statement means; it will do that automatically.  So we can skip the define tactic and just give `h1 h3.left` as a proof of `x âˆˆ B`.  In general, if you have `h1 : A âŠ† B` and `h2 : x âˆˆ A`, then Lean will recognize `h1 h2` as a proof of `x âˆˆ B`.  Thus, the tactic `show x âˆˆ B from h1 h3.left` will complete the first goal.  Once we type this (indented to the same position as the `done` for the first goal), the red squiggle disappears from the first `done`, and the tactic state shows the `No goals` message.  If we then click on the blank line for the second goal, the Infoview pane shows the tactic state for that goal:

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  Â· -- Proof that x âˆˆ B:
    show x âˆˆ B from h1 h3.left
    done
  Â· -- Proof that Â¬x âˆˆ D

    **done::
  done
```
:::

::: {.outpt}
```state
case right
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
âŠ¢ Â¬x âˆˆ D
```
:::
:::

The second goal is a negative statement, and the given `h2` is also a negative statement.  This suggests using proof by contradiction, and achieving the contradiction by contradicting `h2`.

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  Â· -- Proof that x âˆˆ B.
    show x âˆˆ B from h1 h3.left
    done
  Â· -- Proof that Â¬x âˆˆ D.
    contradict h2 with h4
    **done::
  done
```
:::

::: {.outpt}
```state
case right
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
h4 : x âˆˆ D
âŠ¢ âˆƒ (c : U), c âˆˆ C âˆ© D
```
:::
:::

The goal is now an existential statement, and looking at `h3` and `h4` it is clear that the right value to plug in for `c` in the goal is `x`.  The tactic `apply Exists.intro x` will change the goal to `x âˆˆ C âˆ© D` (we have again left off the unnecessary blank at the end of the `apply` tactic).

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  Â· -- Proof that x âˆˆ B.
    show x âˆˆ B from h1 h3.left
    done
  Â· -- Proof that Â¬x âˆˆ D.
    contradict h2 with h4
    apply Exists.intro x
    **done::
  done
```
:::

::: {.outpt}
```state
case right
U : Type
A B C D : Set U
h1 : A âŠ† B
h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D
x : U
h3 : x âˆˆ A âˆ§ x âˆˆ C
h4 : x âˆˆ D
âŠ¢ x âˆˆ C âˆ© D
```
:::
:::

The `define` tactic would now rewrite the goal as `x âˆˆ C âˆ§ x âˆˆ D`, and we could prove this goal by combining `h3.right` and `h4`, using the `And.intro` rule.  But since we know what the result of the `define` tactic will be, there is really no need to use it.  We can just use `And.intro` right away to complete the proof.

::: {.inout}
::: {.inpt}
```lean
theorem Like_Example_3_4_1 (U : Type)
    (A B C D : Set U) (h1 : A âŠ† B)
    (h2 : Â¬âˆƒ (c : U), c âˆˆ C âˆ© D) :
    A âˆ© C âŠ† B \ D := by
  define
  fix x : U
  assume h3 : x âˆˆ A âˆ© C
  define at h3; define
  apply And.intro
  Â· -- Proof that x âˆˆ B.
    show x âˆˆ B from h1 h3.left
    done
  Â· -- Proof that Â¬x âˆˆ D.
    contradict h2 with h4
    apply Exists.intro x
    show x âˆˆ C âˆ© D from And.intro h3.right h4
    done
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

Since `P â†” Q` is shorthand for `(P â†’ Q) âˆ§ (Q â†’ P)`, the strategies given above for conjunctions lead immediately to the following strategies for biconditionals:

#### To prove a goal of the form `P â†” Q`:

::: {.ind}
Prove `P â†’ Q` and `Q â†’ P` separately.
:::

#### To use a given of the form `P â†” Q`:

::: {.ind}
Treat this as two separate givens: `P â†’ Q`, and `Q â†’ P`.
:::

The methods for using these strategies in Lean are similar to those we used above for conjunctions.  If we have `h1 : P â†’ Q` and `h2 : Q â†’ P`, then `Iff.intro h1 h2` is a proof of `P â†” Q`.  Thus, if the goal is `P â†” Q`, then the tactic `apply Iff.intro _ _` will convert this into two separate goals, `P â†’ Q` and `Q â†’ P`.  Once again, you can fill in one of these blanks if you already have a proof of either `P â†’ Q` or `Q â†’ P`, and you can leave out any blanks at the end of the tactic.  If you have a given `h : P â†” Q`, then `h.ltr` is a proof of the left-to-right direction of the biconditional, `P â†’ Q`, and `h.rtl` is a proof of the right-to-left direction, `Q â†’ P`.

Let's try these strategies out in an example.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
âŠ¢ (âˆƒ (x : U), P x) â†”
>>  âˆƒ (x : U), Q x
```
:::
:::

The goal is a biconditional statement, so we begin with the tactic `apply Iff.intro`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  **done::
```
:::

::: {.outpt}
```state
case mp
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
âŠ¢ (âˆƒ (x : U), P x) â†’
>>  âˆƒ (x : U), Q x
case mpr
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
âŠ¢ (âˆƒ (x : U), Q x) â†’
>>  âˆƒ (x : U), P x
```
:::
:::

Once again, we have two goals.  (The case labels this time aren't very intuitive; "mp" stands for "modus ponens" and "mpr" stands for "modus ponens reverse".)  Whenever we have multiple goals, we'll use the bulleted-and-indented style introduced in the last example.  As in *HTPI*, we'll label the proofs of the two goals with `(â†’)` and `(â†)`, representing the two directions of the biconditional symbol `â†”`.  (You can type `â†` in VS Code by typing `\l`, short for "left".)  The first goal is a conditional statement, so we assume the antecedent.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
h2 : âˆƒ (x : U), P x
âŠ¢ âˆƒ (x : U), Q x
```
:::
:::

As usual, when we have an existential given, we use it right away.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
h2 : âˆƒ (x : U), P x
u : U
h3 : P u
âŠ¢ âˆƒ (x : U), Q x
```
:::
:::

Now that we have an object of type `U` in the tactic state, we can use `h1` by applying universal instantiation.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    have h4 : P u â†” Q u := h1 u
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
h2 : âˆƒ (x : U), P x
u : U
h3 : P u
h4 : P u â†” Q u
âŠ¢ âˆƒ (x : U), Q x
```
:::
:::

Looking at `h3` and `h4`, we can now see that we will be able to complete the proof if we assign the value `u` to `x` in the goal.  So our next step is the tactic `apply Exists.intro u`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    have h4 : P u â†” Q u := h1 u
    apply Exists.intro u
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
h2 : âˆƒ (x : U), P x
u : U
h3 : P u
h4 : P u â†” Q u
âŠ¢ Q u
```
:::
:::

To complete the proof, we use the left-to-right direction of `h4`.  We have `h4.ltr : P u â†’ Q u` and `h3 : P u`, so by modus ponens, `h4.ltr h3` proves the goal `Q u`.  Once we enter this step, Lean indicates that the left-to-right proof is complete, and we can position the cursor below the right-to-left bullet to see the tactic state for the second half of the proof.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    have h4 : P u â†” Q u := h1 u
    apply Exists.intro u
    show Q u from h4.ltr h3
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mpr
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
âŠ¢ (âˆƒ (x : U), Q x) â†’
>>  âˆƒ (x : U), P x
```
:::
:::

The second half of the proof is similar to the first.  We begin by assuming `h2 : âˆƒ (x : U), Q x`, and then we use that assumption to obtain `u : U` and `h3 : Q u`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    have h4 : P u â†” Q u := h1 u
    apply Exists.intro u
    show Q u from h4.ltr h3
    done
  Â· -- (â†)
    assume h2 : âˆƒ (x : U), Q x
    obtain (u : U) (h3 : Q u) from h2
    **done::
  done
```
:::

::: {.outpt}
```state
case mpr
U : Type
P Q : Pred U
h1 : âˆ€ (x : U), P x â†” Q x
h2 : âˆƒ (x : U), Q x
u : U
h3 : Q u
âŠ¢ âˆƒ (x : U), P x
```
:::
:::

We can actually shorten the proof by packing a lot into a single step.  See if you can figure out the last line of the completed proof below; we'll give an explanation after the proof.

```lean
example (U : Type) (P Q : Pred U)
    (h1 : âˆ€ (x : U), P x â†” Q x) :
    (âˆƒ (x : U), P x) â†” âˆƒ (x : U), Q x := by
  apply Iff.intro
  Â· -- (â†’)
    assume h2 : âˆƒ (x : U), P x
    obtain (u : U) (h3 : P u) from h2
    have h4 : P u â†” Q u := h1 u
    apply Exists.intro u
    show Q u from h4.ltr h3
    done
  Â· -- (â†)
    assume h2 : âˆƒ (x : U), Q x
    obtain (u : U) (h3 : Q u) from h2
    show âˆƒ (x : U), P x from Exists.intro u ((h1 u).rtl h3)
    done
  done
```

To understand the last step, start with the fact that `h1 u` is a proof of `P u â†” Q u`.  Therefore `(h1 u).rtl` is a proof of `Q u â†’ P u`, so by modus ponens, `(h1 u).rtl h3` is a proof of `P u`.  It follows that `Exists.intro u ((h1 u).rtl h3)` is a proof of `âˆƒ (x : U), P x`, which was the goal.

There is one more style of reasoning that is sometimes used in proofs of biconditional statements.  It is illustrated in Example 3.4.5 of *HTPI*.  Here is that theorem, as it is presented in *HTPI*.

::: {.thm}
Suppose $A$, $B$, and $C$ are sets.  Then $A \cap (B \setmin C) = (A \cap B) \setmin C$.
:::
::: {.proof}
Let $x$ be arbitrary.  Then
\begin{align*}
x \in A \cap (B \setmin C) &\text{ iff } x \in A \wedge x \in B \setmin C\\
&\text{ iff } x \in A \wedge x \in B \wedge x \notin C\\
&\text{ iff } x \in (A \cap B) \wedge x \notin C\\
&\text{ iff } x \in (A \cap B) \setmin C.
\end{align*}
Thus, $\forall x(x \in A \cap (B \setmin C) \leftrightarrow x \in (A \cap B) \setmin C)$, so $A \cap (B \setmin C) = (A \cap B) \setmin C$. [&nbsp;â–¡]{.excl}\qedhere
:::

This proof is based on a fundamental principle of set theory that says that if two sets have exactly the same elements, then they are equal.  This principle is called the *axiom of extensionality*, and it is what justifies the inference, in the last sentence, from $\forall x(x \in A \cap (B \setmin C) \leftrightarrow x \in (A \cap B) \setmin C)$ to $A \cap (B \setmin C) = (A \cap B) \setmin C$.

The heart of the proof is a string of equivalences that, taken together, establish the biconditional statement $x \in A \cap (B \setmin C) \leftrightarrow x \in (A \cap B) \setmin C$.  One can also use this technique to prove a biconditional statement in Lean.  This time we'll simply present the complete proof first, and then explain it afterwards.

```lean
theorem Example_3_4_5 (U : Type)
    (A B C : Set U) : A âˆ© (B \ C) = (A âˆ© B) \ C := by
  apply Set.ext
  fix x : U
  show x âˆˆ A âˆ© (B \ C) â†” x âˆˆ (A âˆ© B) \ C from
    calc x âˆˆ A âˆ© (B \ C)
        â†” x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C) := Iff.refl _
      _ â†” (x âˆˆ A âˆ§ x âˆˆ B) âˆ§ x âˆ‰ C := and_assoc.symm
      _ â†” x âˆˆ (A âˆ© B) \ C := Iff.refl _
  done
```

The name of the axiom of extensionality in Lean is `Set.ext`, and it is applied in the first step of the Lean proof.  As usual, the `apply` tactic works backwards from the goal.  In other words, after the first line of the proof, the goal is `âˆ€ (x : U), x âˆˆ A âˆ© (B \ C) â†” x âˆˆ (A âˆ© B) \ C`, because by `Set.ext`, the conclusion of the theorem would follow from this statement.  The rest of the proof then proves this goal by introducing an arbitrary `x` of type `U` and then proving the biconditional by stringing together several equivalences, exactly as in the *HTPI* proof.

The proof of the biconditional is called a *calculational proof*, and it is introduced by the keyword `calc`.  The calculational proof consists of a string of biconditional statements, each of which is provided with a proof.  You can think of the underscore on the left side of each biconditional after the first as standing for the right side of the previous biconditional.

The proofs of the individual biconditionals in the calculational proof require some explanation.  Lean has a large library of theorems that it knows, and you can use those theorems in your proofs.  In particular, `Iff.refl` and `and_assoc` are names of theorems in Lean's library.  You can find out what any theorem says by using the Lean command `#check`.  (Commands that ask Lean for a response generally start with the character `#`.)  If you type `#check Iff.refl` in a Lean file, you will see Lean's response in the Infoview pane:  `Iff.refl (a : Prop) : a â†” a`.  What this tells us is that Lean already knows the theorem

```lean
theorem Iff.refl (a : Prop) : a â†” a
```

(This theorem says that "iff" has a property called *reflexivity*; we'll discuss reflexivity in Chapter 4.)  When variables are declared in the statement of a theorem, it is understood that they can stand for anything of the appropriate type (see Section 3.1 of *HTPI*).  Thus, the theorem `Iff.refl` can be thought of as establishing the truth of the statement `âˆ€ (a : Prop), a â†” a`.  In fact, you can get Lean to report the meaning of the theorem in this form with the command `#check @Iff.refl`.  What this means is that, in any proof, Lean let's you treat `Iff.refl` as a proof of the statement `âˆ€ (a : Prop), a â†” a`.  Thus, by universal instantiation, for any proposition `a`, Lean will recognize `Iff.refl a` as a proof of `a â†” a`.  This is used to justify the first biconditional in the calculational proof.

But wait!  The first biconditional in the calculational proof is `x âˆˆ A âˆ© (B \ C) â†” x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C)`, which does not have the form `a â†” a`.  How can it be justified by the theorem `Iff.refl`?  Recall that Lean doesn't need to be told to write out definitions of mathematical notation; it does that automatically.  When the definitions of the set theory notation are written out, the first biconditional in the calculational proof becomes `x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C) â†” x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C)`, which *does* have the form `a â†” a`, so it can be proven with the term-mode proof `Iff.refl _`.  Note that we are using an underscore here to ask Lean to figure out what to plug in for `a`.  This saves us the trouble of writing out the full term-mode proof, which would be `Iff.refl (x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C))`.  The lesson of this example is that the theorem `Iff.refl` is more powerful than it looks.  Not only can we use `Iff.refl _` to prove statements of the form `a â†” a`, we can also use it to prove statements of the form `a â†” a'`, if `a` and `a'` reduce to the same thing when definitions are filled in.  We say in this case that `a` and `a'` are *definitionally equal*.  This explains the third line of the calculational proof, which is also justified by the proof `Iff.refl _`.

The second line uses the theorem `and_assoc`.  If you type `#check and_assoc`, you will get this response from Lean:

::: {.ind}
```
and_assoc {a b c : Prop} : (a âˆ§ b) âˆ§ c â†” a âˆ§ b âˆ§ c
```
:::

Once again, it is understood that the variables `a`, `b`, and `c` can stand for any propositions, as you can see by giving the command `#check @and_assoc`.  This generates the response

::: {.ind}
```
@and_assoc : âˆ€ {a b c : Prop}, (a âˆ§ b) âˆ§ c â†” a âˆ§ b âˆ§ c
```
:::

which is shorthand for

::: {.ind}
```
@and_assoc : âˆ€ {a : Prop}, âˆ€ {b : Prop}, âˆ€ {c : Prop},
              (a âˆ§ b) âˆ§ c â†” a âˆ§ (b âˆ§ c)
```
:::

Recall that the curly braces indicate that `a`, `b`, and `c` are implicit arguments, and that Lean groups the logical connectives to the right, which means that it interprets `a âˆ§ b âˆ§ c` as `a âˆ§ (b âˆ§ c)`.  This is the associative law for "and" (see Section 1.2 of *HTPI*).  Since `a`, `b`, and `c` are implicit, Lean will recognize `and_assoc` as a proof of any statement of the form `(a âˆ§ b) âˆ§ c â†” a âˆ§ (b âˆ§ c)`, where `a`, `b`, and `c` can be replaced with any propositions.  Lean doesn't need to be told what propositions are being used as `a`, `b`, and `c`; it will figure that out for itself.  Unfortunately, the second biconditional in the calculational proof is `x âˆˆ A âˆ§ (x âˆˆ B âˆ§ x âˆ‰ C) â†” (x âˆˆ A âˆ§ x âˆˆ B) âˆ§ x âˆ‰ C`, which has the form `a âˆ§ (b âˆ§ c) â†” (a âˆ§ b) âˆ§ c`, not `(a âˆ§ b) âˆ§ c â†” a âˆ§ (b âˆ§ c)`.  (Notice that the first of these biconditionals is the same as the second except that the left and right sides have been swapped.)  To account for this discrepancy, we use the fact that if `h` is a proof of any biconditional `P â†” Q`, then `h.symm` is a proof of `Q â†” P`.  Thus `and_assoc.symm` proves the second biconditional in the calculational proof.  (By the way, the *HTPI* proof avoids any mention of the associativity of "and" by simply leaving out parentheses in the conjunction $x \in A \wedge x \in B \wedge x \notin C$.  As explained in Section 1.2 of *HTPI*, this represents an implicit use of the associativity of "and.")

You can get a better understanding of the first step of our last proof by typing `#check @Set.ext`.  The result is

::: {.ind}
```
@Set.ext : âˆ€ {Î± : Type u_1} {a b : Set Î±},
            (âˆ€ (x : Î±), x âˆˆ a â†” x âˆˆ b) â†’ a = b
```
:::

which is shorthand for

::: {.ind}
```
@Set.ext : âˆ€ {Î± : Type u_1}, âˆ€ {a : Set Î±}, âˆ€ {b : Set Î±},
            (âˆ€ (x : Î±), x âˆˆ a â†” x âˆˆ b) â†’ a = b
```
:::

Ignoring the `u_1`, whose significance won't be important to us, this means that `Set.ext` can be used to prove any statement of the form `(âˆ€ (x : Î±), x âˆˆ a â†” x âˆˆ b) â†’ a = b`, where `Î±` can be replaced by any type and `a` and `b` can be replaced by any sets of objects of type `Î±`.  Make sure you understand how this explains the effect of the tactic `apply Set.ext` in the first step of our last proof.  Almost all of our proofs that two sets are equal will start with `apply Set.ext`.

Notice that in Lean's responses to both `#check @and_assoc` and `#check @Set.ext`, multiple universal quantifiers in a row were grouped together and written as a single universal quantifier followed by a list of variables (with types).  Lean allows this notational shorthand for any sequence of consecutive quantifiers, as long as they are all of the same kind (all existential or all universal), and we will use this notation from now on.

### Exercises

::: {.numex arguments="1"}
```lean
theorem Exercise_3_4_2 (U : Type) (A B C : Set U)
    (h1 : A âŠ† B) (h2 : A âŠ† C) : A âŠ† B âˆ© C := by
  
  **done::
```
:::

::: {.numex arguments="2"}
```lean
theorem Exercise_3_4_4 (U : Type) (A B C : Set U)
    (h1 : A âŠ† B) (h2 : A âŠˆ C) : B âŠˆ C := by
  
  **done::
```
:::

::: {.numex arguments="3"}
```lean
theorem Exercise_3_3_16 (U : Type) (B : Set U)
    (F : Set (Set U)) : F âŠ† ð’« B â†’ â‹ƒâ‚€F âŠ† B := by
  
  **done::
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_3_17 (U : Type) (F G : Set (Set U))
    (h1 : âˆ€ (A : Set U), A âˆˆ F â†’ âˆ€ (B : Set U), B âˆˆ G â†’ A âŠ† B) :
    â‹ƒâ‚€F âŠ† â‹‚â‚€G := by
  
  **done::
```
:::

::: {.numex arguments="5"}
```lean
theorem Exercise_3_4_7 (U : Type) (A B : Set U) :
    ð’« (A âˆ© B) = ð’« A âˆ© ð’« B := by

  **done::
```
:::

::: {.numex arguments="6"}
```lean
theorem Exercise_3_4_17 (U : Type) (A : Set U) : A = â‹ƒâ‚€(ð’« A) := by

  **done::
```
:::

::: {.numex arguments="7"}
```lean
theorem Exercise_3_4_18a (U : Type) (F G : Set (Set U)) :
    â‹ƒâ‚€(F âˆ© G) âŠ† (â‹ƒâ‚€F) âˆ© (â‹ƒâ‚€G) := by
  
  **done::
```
:::

::: {.numex arguments="8"}
```lean
theorem Exercise_3_4_19 (U : Type) (F G : Set (Set U)) :
    (â‹ƒâ‚€F) âˆ© (â‹ƒâ‚€G) âŠ† â‹ƒâ‚€(F âˆ© G) â†”
      âˆ€ (A B : Set U), A âˆˆ F â†’ B âˆˆ G â†’ A âˆ© B âŠ† â‹ƒâ‚€(F âˆ© G) := by
  
  **done::
```
:::

## 3.5.  Proofs Involving Disjunctions

A common proof method for dealing with givens or goals that are disjunctions is *proof by cases*.  Here's how it works.

#### To use a given of the form `P âˆ¨ Q`:

::: {.ind}
Break your proof into cases.  For case 1, assume that `P` is true and use this assumption to prove the goal.  For case 2, assume that `Q` is true and prove the goal.
:::

In Lean, you can break a proof into cases by using the `by_cases` tactic.  If you have a given `h : P âˆ¨ Q`, then the tactic `by_cases on h` will break your proof into two cases.  For the first case, the given `h` will be changed to `h : P`, and for the second, it will be changed to `h : Q`; the goal for both cases will be the same as the original goal.  Thus, the effect of the `by_cases on h` tactic is as follows:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
h : P âˆ¨ Q
âŠ¢ goal
```
:::

::: {.aft}
```state
case Case_1
>> â‹®
h : P
âŠ¢ goal
case Case_2
>> â‹®
h : Q
âŠ¢ goal
```
:::
:::

Notice that the original given `h : P âˆ¨ Q` gets *replaced* by `h : P` in case 1 and `h : Q` in case 2.  This is usually what is most convenient, but if you write `by_cases on h with h1`, then the original given `h` will be preserved, and new givens `h1 : P` and `h1 : Q` will be added to cases 1 and 2, respectively.  If you want different names for the new givens in the two cases, then use `by_cases on h with h1, h2` to add the new given `h1 : P` in case 1 and `h2 : Q` in case 2.

You can follow `by_cases on` with any proof of a disjunction, even if that proof is not just a single identifier.  In that cases you will want to add `with` to specify the identifier or identifiers to be used for the new assumptions in the two cases.  Another variant is that you can use the tactic `by_cases h : P` to break your proof into two cases, with the new assumptions being `h : P` in case 1 and `h : Â¬P` in case 2.  In other words, the effect of `by_cases h : P` is the same as adding the new given `h : P âˆ¨ Â¬P` (which, of course, is a tautology) and then using the tactic `by_cases on h`.

There are two introduction rules that you can use in Lean to prove a goal of the form `P âˆ¨ Q`.  If you have `h : P`, then Lean will accept `Or.intro_left h` as a proof of `P âˆ¨ Q`, and if you have `h : Q`, then `Or.intro_right h` is a proof of `P âˆ¨ Q`.  There are shortened forms `Or.inl` and `Or.inr` for `Or.intro_left` and `Or.intro_right`, respectively.

Often, when your goal has the form `P âˆ¨ Q`, you will be unable to prove `P`, and also unable to prove `Q`.  Proof by cases can help in that situation as well.

#### To prove a goal of the form `P âˆ¨ Q`:

::: {.ind}
Break your proof into cases.  In each case, either prove `P` or prove `Q`.
:::

Example 3.5.2 from *HTPI* illustrates these strategies:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
    (U : Type) (A B C : Set U) :
    A \ (B \ C) âŠ† (A \ B) âˆª C := by

  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
âŠ¢ A \ (B \ C) âŠ† A \ B âˆª C
```
:::
:::

The `define` tactic would rewrite the goal as `âˆ€ â¦ƒa : Uâ¦„, a âˆˆ A \ (B \ C) â†’ a âˆˆ A \ B âˆª C`, which suggests that our next two tactics should be `fix x : U` and `assume h1 : x âˆˆ A \ (B \ C)`.  But as we have seen before, if you know what the result of the `define` tactic is going to be, then there is usually no need to use it.  After introducing `x` as an arbitrary element of `A \ (B \ C)`, we write out the definitions of our new given and goal to help guide our next strategy choice:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
    (U : Type) (A B C : Set U) :
    A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
âŠ¢ x âˆˆ A \ B âˆ¨ x âˆˆ C
```
:::
:::

The goal is now a disjunction, which suggests that proof by cases might be helpful.  But what cases should we use?  The key is to look at the meaning of the right half of the given `h1`.  The meaning of `Â¬x âˆˆ B \ C` is `Â¬(x âˆˆ B âˆ§ x âˆ‰ C)`, which, by one of the De Morgan laws, is equivalent to `x âˆ‰ B âˆ¨ x âˆˆ C`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
    (U : Type) (A B C : Set U) :
    A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  have h2 : Â¬x âˆˆ B \ C := h1.right
  define at h2; demorgan at h2
            --Now h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
âŠ¢ x âˆˆ A \ B âˆ¨ x âˆˆ C
```
:::
:::

The new given `h2` is now a disjunction, which suggests what cases we should use:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
    (U : Type) (A B C : Set U) :
    A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  have h2 : Â¬x âˆˆ B \ C := h1.right
  define at h2; demorgan at h2
            --Now h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
  by_cases on h2
  **done::
```
:::

::: {.outpt}
```state
case Case_1
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
h2 : Â¬x âˆˆ B
âŠ¢ x âˆˆ A \ B âˆ¨ x âˆˆ C
case Case_2
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
h2 : x âˆˆ C
âŠ¢ x âˆˆ A \ B âˆ¨ x âˆˆ C
```
:::
:::

Of course, now that we have two goals, we will introduce bullets labeling the two parts of the proof as case 1 and case 2.  Looking at the givens `h1` and `h2` in both cases, it is not hard to see that we should be able to prove `x âˆˆ A \ B` in case 1 and `x âˆˆ C` in case 2.  Thus, in case 1 we will be able to give a proof of the goal that has the form `Or.inl _`, where the blank will be filled in with a proof of `x âˆˆ A \ B`, and in case 2 we can use `Or.inr _`, filling in the blank with a proof of `x âˆˆ C`.  This suggests that we should use the tactics `apply Or.inl` in case 1 and `apply Or.inr` in case 2.  Focusing first on case 1, we get:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
(U : Type) (A B C : Set U) :
A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  have h2 : Â¬x âˆˆ B \ C := h1.right
  define at h2; demorgan at h2
            --Now h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
  by_cases on h2
  Â· -- Case 1.  h2 : Â¬x âˆˆ B
    apply Or.inl
    **done::
  Â· -- Case 2.  h2 : x âˆˆ C

    **done::
  done

```
:::

::: {.outpt}
```state
case Case_1.h
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
h2 : Â¬x âˆˆ B
âŠ¢ x âˆˆ A \ B
```
:::
:::

Notice that the tactic `apply Or.inl` has changed the goal for case 1 to the left half of the original goal, `x âˆˆ A \ B`.  Since this means `x âˆˆ A âˆ§ x âˆ‰ B`, we can complete case 1 by combining `h1.left` with `h2`, and then we can move on to case 2.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
(U : Type) (A B C : Set U) :
A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  have h2 : Â¬x âˆˆ B \ C := h1.right
  define at h2; demorgan at h2
            --Now h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
  by_cases on h2
  Â· -- Case 1.  h2 : Â¬x âˆˆ B
    apply Or.inl
    show x âˆˆ A \ B from And.intro h1.left h2
    done
  Â· -- Case 2.  h2 : x âˆˆ C

    **done::
  done

```
:::

::: {.outpt}
```state
case Case_2
U : Type
A B C : Set U
x : U
h1 : x âˆˆ A âˆ§ Â¬x âˆˆ B \ C
h2 : x âˆˆ C
âŠ¢ x âˆˆ A \ B âˆ¨ x âˆˆ C
```
:::
:::

Case 2 is similar, using `Or.inr` and `h2`

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_5_2
(U : Type) (A B C : Set U) :
A \ (B \ C) âŠ† (A \ B) âˆª C := by
  fix x : U
  assume h1 : x âˆˆ A \ (B \ C)
  define; define at h1
  have h2 : Â¬x âˆˆ B \ C := h1.right
  define at h2; demorgan at h2
            --Now h2 : Â¬x âˆˆ B âˆ¨ x âˆˆ C
  by_cases on h2
  Â· -- Case 1.  h2 : Â¬x âˆˆ B
    apply Or.inl
    show x âˆˆ A \ B from And.intro h1.left h2
    done
  Â· -- Case 2.  h2 : x âˆˆ C
    apply Or.inr
    show x âˆˆ C from h2
    done
  done

```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

There is a second strategy that is often useful to prove a goal of the form `P âˆ¨ Q`.  It is motivated by the fact that `P âˆ¨ Q` is equivalent to both `Â¬P â†’ Q` and `Â¬Q â†’ P`.

#### To prove a goal of the form `P âˆ¨ Q`:

::: {.ind}
Assume that `P` is false and prove `Q`, or assume that `Q` is false and prove `P`.
:::

If your goal is `P âˆ¨ Q`, then the Lean tactic `or_left with h` will add the new given `h : Â¬Q` to the tactic state and set the goal to be `P`, and `or_right with h` will add `h : Â¬P` to the tactic state and set the goal to be `Q`.  For example, here is the effect of the tactic `or_left with h`:

::: {.lftrt}
::: {.bef}
```state
>> â‹®
âŠ¢ P âˆ¨ Q
```
:::

::: {.aft}
```state
>> â‹®
h : Â¬Q
âŠ¢ P
```
:::
:::


Notice that `or_left` and `or_right` have the same effect as `apply Or.inl` and `apply Or.inr`, except that each adds a new given to the tactic state.  Sometimes you can tell in advance that you won't need the extra given, and in that case the tactics `apply Or.inl` and `apply Or.inr` can be useful.  For example, that was the case in the example above.  But if you think the extra given might be useful, you are better off using `or_left` or `or_right`.  Here's an example illustrating this.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U)
    (h1 : A \ B âŠ† C) : A âŠ† B âˆª C := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A \ B âŠ† C
âŠ¢ A âŠ† B âˆª C
```
:::
:::

Of course, we begin by letting `x` be an arbitrary element of `A`.  Writing out the meaning of the new goal shows that it is a disjunction.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U)
    (h1 : A \ B âŠ† C) : A âŠ† B âˆª C := by
  fix x : U
  assume h2 : x âˆˆ A
  define
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A \ B âŠ† C
x : U
h2 : x âˆˆ A
âŠ¢ x âˆˆ B âˆ¨ x âˆˆ C
```
:::
:::

Looking at the givens `h1` and `h2`, we see that if we assume `x âˆ‰ B`, then we should be able to prove `x âˆˆ C`.  This suggests that we should use the `or_right` tactic.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U)
    (h1 : A \ B âŠ† C) : A âŠ† B âˆª C := by
  fix x : U
  assume h2 : x âˆˆ A
  define
  or_right with h3
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A \ B âŠ† C
x : U
h2 : x âˆˆ A
h3 : Â¬x âˆˆ B
âŠ¢ x âˆˆ C
```
:::
:::

We can now complete the proof.  Notice that `h1 _` will be a proof of the goal `x âˆˆ C`, if we can fill in the blank with a proof of `x âˆˆ A \ B`.  Since `x âˆˆ A \ B` means `x âˆˆ A âˆ§ Â¬x âˆˆ B`, we can prove it with the expression `And.intro h2 h3`.

::: {.inout}
::: {.inpt}
```lean
example (U : Type) (A B C : Set U)
    (h1 : A \ B âŠ† C) : A âŠ† B âˆª C := by
  fix x : U
  assume h2 : x âˆˆ A
  define
  or_right with h3
  show x âˆˆ C from h1 (And.intro h2 h3)
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

The fact that `P âˆ¨ Q` is equivalent to both `Â¬P â†’ Q` and `Â¬Q â†’ P` also suggests another strategy for using a given that is a disjunction.

#### To use a given of the form `P âˆ¨ Q`:

::: {.ind}
If you are also given `Â¬P`, or you can prove that `P` is false, then you can use this given to conclude that `Q` is true.  Similarly, if you are given `Â¬Q` or can prove that `Q` is false, then you can conclude that `P` is true.
:::

This strategy is a rule of inference called *disjunctive syllogism*, and the tactic for using this strategy in Lean is called `disj_syll`.  If you have `h1 : P âˆ¨ Q` and `h2 : Â¬P`, then the tactic `disj_syll h1 h2` will change `h1` to `h1 : Q`; if instead you have `h2 : Â¬Q`, then `disj_syll h1 h2` will change `h1` to `h1 : P`.  Notice that, as with the `by_cases` tactic, the given `h1` gets *replaced* with the conclusion of the rule.  The tactic `disj_syll h1 h2 with h3` will preserve the original `h1` and introduce the conclusion as a new given with the identifier `h3`.  Also, as with the `by_cases` tactic, either `h1` or `h2` can be a complex proof rather than simply an identifier (although in that case it must be enclosed in parentheses, so that Lean can tell where `h1` ends and `h2` begins).  The only requirement is that `h1` must be a proof of a disjunction, and `h2` must be a proof of the negation of one side of the disjunction.  If `h1` is not simply an identifier, then you will want to use `with` to specify the identifier to be used for the conclusion of the rule.

Here's an example illustrating the use of the disjunctive syllogism rule.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by

  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : Â¬âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
âŠ¢ A âŠ† C
```
:::
:::

Of course, we begin by introducing an arbitrary element of `A`.  We also rewrite `h2` as an equivalent positive statement.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  quant_neg at h2
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  Â¬x âˆˆ A âˆ© B
a : U
h3 : a âˆˆ A
âŠ¢ a âˆˆ C
```
:::
:::

We can now make two inferences by combining `h1` with `h3` and by applying `h2` to `a`.  To see how to use the inferred statements, we write out their definitions, and since one of them is a negative statement, we reexpress it as an equivalent positive statement.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  quant_neg at h2
  have h4 : a âˆˆ B âˆª C := h1 h3
  have h5 : a âˆ‰ A âˆ© B := h2 a
  define at h4
  define at h5; demorgan at h5
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : âˆ€ (x : U),
>>  Â¬x âˆˆ A âˆ© B
a : U
h3 : a âˆˆ A
h4 : a âˆˆ B âˆ¨ a âˆˆ C
h5 : Â¬a âˆˆ A âˆ¨ Â¬a âˆˆ B
âŠ¢ a âˆˆ C
```
:::
:::

Both `h4` and `h5` are disjunctions, and looking at `h3` we see that the disjunctive syllogism rule can be applied.  From `h3` and `h5` we can draw the conclusion `Â¬a âˆˆ B`, and then combining that conclusion with `h4` we can infer `a âˆˆ C`.  Since that is the goal, we are done.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  quant_neg at h2
  have h4 : a âˆˆ B âˆª C := h1 h3
  have h5 : a âˆ‰ A âˆ© B := h2 a
  define at h4
  define at h5; demorgan at h5
  disj_syll h5 h3  --Now h5 : Â¬a âˆˆ B
  disj_syll h4 h5  --Now h4 : a âˆˆ C
  show a âˆˆ C from h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

We're going to redo the last example, to illustrate another useful technique in Lean.  We start with some of the same steps as before.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  have h4 : a âˆˆ B âˆª C := h1 h3
  define at h4
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : Â¬âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
a : U
h3 : a âˆˆ A
h4 : a âˆˆ B âˆ¨ a âˆˆ C
âŠ¢ a âˆˆ C
```
:::
:::

At this point, you might see a possible route to the goal:  from `h2` and `h3` we should be able to prove that `a âˆ‰ B`, and then, combining that with `h4` by the disjunctive syllogism rule, we should be able to deduce the goal `a âˆˆ C`.  Let's try writing the proof that way.

::: {.inout}
::: {.inpt}
```lean
??example::
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  have h4 : a âˆˆ B âˆª C := h1 h3
  define at h4
  have h5 : a âˆ‰ B := sorry
  disj_syll h4 h5  --Now h4 : a âˆˆ C
  show a âˆˆ C from h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

We have introduced a new idea in this proof.  The justification we have given for introducing `h5 : a âˆ‰ B` is `sorry`.  You might think of this as meaning "Sorry, I'm not going to give a justification for this statement, but please accept it anyway."  Of course, this is cheating; in a complete proof, every step must be justified.  Lean accepts `sorry` as a proof of any statement, but it displays it in red to warn you that you're cheating.  It also puts a brown squiggle under the keyword `example` and it puts the message `declaration uses 'sorry'` in the Infoview, to warn you that, although the proof has reached the goal, it is not fully justified.

Although writing the proof this way is cheating, it is a convenient way to see that our plan of attack for this proof is reasonable.  Lean has accepted the proof, except for the warning that we have used `sorry`.  So now we know that if we go back and replace `sorry` with a proof of `a âˆ‰ B`, then we will have a complete proof.

The proof of `a âˆ‰ B` is hard enough that it is easier to do it in tactic mode rather than term mode.  So we will begin the proof as we always do for tactic-mode proofs: we replace `sorry` with `by`, leave a blank line, and then put `done`, indented further than the surrounding text.  When we put the cursor on the blank line before `done`, we see the tactic state for our "proof within a proof."

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  have h4 : a âˆˆ B âˆª C := h1 h3
  define at h4
  have h5 : a âˆ‰ B := by

    **done::
  disj_syll h4 h5  --Now h4 : a âˆˆ C
  show a âˆˆ C from h4
  done
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : Â¬âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
a : U
h3 : a âˆˆ A
h4 : a âˆˆ B âˆ¨ a âˆˆ C
âŠ¢ Â¬a âˆˆ B
```
:::
:::

Note that `h5 : a âˆ‰ B` is not a given in the tactic state, because we have not yet justified it; in fact, `Â¬a âˆˆ B` is the goal.  This goal is a negative statement, and `h2` is also negative.  This suggests that we could try using proof by contradiction, achieving the contradiction by contradicting `h2`.  So we use the tactic `contradict h2 with h6`.

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  have h4 : a âˆˆ B âˆª C := h1 h3
  define at h4
  have h5 : a âˆ‰ B := by
    contradict h2 with h6
    **done::
  disj_syll h4 h5  --Now h4 : a âˆˆ C
  show a âˆˆ C from h4
  done
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : A âŠ† B âˆª C
h2 : Â¬âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
a : U
h3 : a âˆˆ A
h4 : a âˆˆ B âˆ¨ a âˆˆ C
h6 : a âˆˆ B
âŠ¢ âˆƒ (x : U), x âˆˆ A âˆ© B
```
:::
:::

Looking at `h3` and `h6`, we see that the right value to plug in for `x` in the goal is `a`.  In fact, `Exists.intro a _` will prove the goal, if we can fill in the blank with a proof of `a âˆˆ A âˆ© B`.  Since this means `a âˆˆ A âˆ§ a âˆˆ B`, we can prove it with `And.intro h3 h6`.  Thus, we can complete the proof in one more step:

::: {.inout}
::: {.inpt}
```lean
example
    (U : Type) (A B C : Set U) (h1 : A âŠ† B âˆª C)
    (h2 : Â¬âˆƒ (x : U), x âˆˆ A âˆ© B) : A âŠ† C := by
  fix a : U
  assume h3 : a âˆˆ A
  have h4 : a âˆˆ B âˆª C := h1 h3
  define at h4
  have h5 : a âˆ‰ B := by
    contradict h2 with h6
    show âˆƒ (x : U), x âˆˆ A âˆ© B from
      Exists.intro a (And.intro h3 h6)
    done
  disj_syll h4 h5  --Now h4 : a âˆˆ C
  show a âˆˆ C from h4
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

The red squiggle has disappeared from the word `done`, indicating that the proof is complete.

It was not really necessary for us to use `sorry` when writing this proof.  We could have simply written the steps in order,  exactly as they appear above.  Any time you use the `have` tactic with a conclusion that is difficult to justify, you have a choice.  You can establish the `have` with `sorry`, complete the proof, and then return and fill in a justification for the `have`, as we did in the example above.  Or, you can justify the `have` right away by typing `by` after `:=` and then plunging into the "proof within in a proof."  Once you complete the inner proof, you can continue with the original proof.

And in case you were wondering: yes, if the inner proof uses the `have` tactic with a statement that is hard to justify, then you can write a "proof within a proof within a proof"!

### Exercises

In each case, replace `sorry` with a proof.

::: {.numex arguments="1"}
```lean
theorem Exercise_3_5_2 (U : Type) (A B C : Set U) :
    (A âˆª B) \ C âŠ† A âˆª (B \ C) := sorry
```
:::

::: {.numex arguments="2"}
```lean
theorem Exercise_3_5_5 (U : Type) (A B C : Set U)
    (h1 : A âˆ© C âŠ† B âˆ© C) (h2 : A âˆª C âŠ† B âˆª C) : A âŠ† B := sorry
```
:::

::: {.numex arguments="3"}
```lean
theorem Exercise_3_5_7 (U : Type) (A B C : Set U) :
    A âˆª C âŠ† B âˆª C â†” A \ C âŠ† B \ C := sorry
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_5_8 (U : Type) (A B : Set U) :
    ð’« A âˆª ð’« B âŠ† ð’« (A âˆª B) := sorry
```
:::

::: {.numex arguments="5"}
```lean
theorem Exercise_3_5_17b (U : Type) (F : Set (Set U)) (B : Set U) :
    B âˆª (â‹‚â‚€ F) =
      â‹‚â‚€ { X : Set U | âˆƒ (A : Set U), A âˆˆ F âˆ§ X = B âˆª A} := sorry
```
:::

::: {.numex arguments="6"}
```lean
theorem Exercise_3_5_18 (U : Type) (F G H : Set (Set U))
    (h1 : âˆ€ (A : Set U), A âˆˆ F â†’ âˆ€ (B : Set U), B âˆˆ G â†’ A âˆª B âˆˆ H) :
    â‹‚â‚€H âŠ† (â‹‚â‚€F) âˆª (â‹‚â‚€G) := sorry
```
:::

::: {.numex arguments="7"}
```lean
theorem Exercise_3_5_24a (U : Type) (A B C : Set U) :
    (A âˆª B) â–³ C âŠ† (A â–³ C) âˆª (B â–³ C) := sorry
```
:::

## 3.6.  Existence and Uniqueness Proofs

Recall that `âˆƒ! (x : U), P x` means that there is exactly one `x` of type `U` such that `P x` is true.  One way to deal with a given or goal of this form is to use the `define` tactic to rewrite it as the equivalent statement `âˆƒ (x : U), P x âˆ§ âˆ€ (x_1 : U), P x_1 â†’ x_1 = x`.  You can then apply techniques discussed previously in this chapter.  However, there are also proof techniques, and corresponding Lean tactics, for working directly with givens and goals of this form.

Often a goal of the form `âˆƒ! (x : U), P x` is proven by using the following strategy.  This is a slight rephrasing of the strategy presented in *HTPI*.  The rephrasing is based on the fact that for any propositions `A`, `B`, and `C`, `A âˆ§ B â†’ C` is equivalent to `A â†’ B â†’ C` (you can check this equivalence by making a truth table).  The second of these statements is usually easier to work with in Lean than the first one, so we will often rephrase statements that have the form `A âˆ§ B â†’ C` as `A â†’ B â†’ C`.  That's what we have done here, as you will see if you compare the strategy stated below to the one in *HTPI*.

#### To prove a goal of the form `âˆƒ! (x : U), P x`:

::: {.ind}
Prove `âˆƒ (x : U), P x` and `âˆ€ (x_1 x_2 : U), P x_1 â†’ P x_2 â†’ x_1 = x_2`.  The first of these goals says that there exists an `x` such that `P x` is true, and the second says that it is unique.  The two parts of the proof are therefore sometimes labeled *existence* and *uniqueness*.
:::

To apply this strategy in a Lean proof, we use the tactic `exists_unique`.  We'll illustrate this with the theorem from Example 3.6.2 in *HTPI*.  Here's how that theorem and its proof are presented in *HTPI*:

::: {.thm}
There is a unique set $A$ such that for every set $B$, $A \cup B = B$.
:::
::: {.proof}
Existence:  Clearly $\forall B(\varnothing \cup B = B)$, so $\varnothing$ has the required property.

Uniqueness:  Suppose $\forall B(C \cup B = B)$ and $\forall B(D \cup B = B)$.  Applying the first of these assumptions to $D$ we see that $C \cup D = D$, and applying the second to $C$ we get $D \cup C = C$.  But clearly $C \cup D = D \cup C$, so $C = D$. [&nbsp;â–¡]{.excl}\qedhere
:::

You will notice that there are two statements in this proof that are described as "clearly" true.  This brings up one of the difficulties with proving theorems in Lean: things that are clear to *us* are not necessarily clear to *Lean*!  There are two ways to deal with such "clear" statements.  The first is to see if the statement is in the library of theorems that Lean knows.  The second is to prove the statement as a preliminary theorem that can then be used in the proof of our main theorem.  We'll take the second approach here, since proving these "clear" facts will give us more practice with Lean proofs, but later we'll have more to say about searching for statements in Lean's theorem library.

The first theorem we need says that for every set `B`, `âˆ… âˆª B = B`, and it brings up a subtle issue: in Lean, the symbol `âˆ…` is ambiguous!  The reason for this is Lean's strict typing rules.  For each type `U`, there is an empty set of type `Set U`.  There is, for example, the set of type `Set Nat` that contains no natural numbers, and also the set of type `Set Real` that contains no real numbers.  To Lean, these are different sets, because they have different types.  Which one does the symbol `âˆ…` denote?  The answer will be different in different contexts.  Lean can sometimes figure out from context which empty set you have in mind, but if it can't, then you have to tell it explicitly by writing `(âˆ… : Set U)` rather than `âˆ…`.

With that preparation, we are ready to prove our first preliminary theorem.  To avoid problems with ambiguity, we'll tell Lean explicitly which empty set we have in mind in this theorem.  Since the goal is an equation between sets, our first step is to use the tactic `apply Set.ext`.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  **done::
```
:::

::: {.outpt}
```state
case h
U : Type
B : Set U
âŠ¢ âˆ€ (x : U),
>>  x âˆˆ âˆ… âˆª B â†” x âˆˆ B
```
:::
:::

Based on the form of the goal, our next two tactics should be `fix x : U` and `apply Iff.intro`.  This leaves us with two goals, corresponding to the two directions of the biconditional, but we'll focus first on just the left-to-right direction.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)

    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case h.mp
U : Type
B : Set U
x : U
âŠ¢ x âˆˆ âˆ… âˆª B â†’ x âˆˆ B
```
:::
:::

Of course, our next step is to assume `x âˆˆ (âˆ… : Set U) âˆª B`.  To help us see how to move forward, we also write out the definition of this assumption.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case h.mp
U : Type
B : Set U
x : U
h1 : x âˆˆ âˆ… âˆ¨ x âˆˆ B
âŠ¢ x âˆˆ B
```
:::
:::

Now you should see a way to complete the proof: the statement `x âˆˆ âˆ…` is false, so we should be able to apply the disjunctive syllogism rule to `h1` to infer the goal `x âˆˆ B`.  To carry out this plan, we'll first have to prove `x âˆ‰ (âˆ… : Set U)`.  We'll use the `have` tactic, and since there's no obvious term-mode proof to justify it, we'll try a tactic-mode proof.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    have h2 : x âˆ‰ (âˆ… : Set U) := by

      **done::
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
U : Type
B : Set U
x : U
h1 : x âˆˆ âˆ… âˆ¨ x âˆˆ B
âŠ¢ Â¬x âˆˆ âˆ…
```
:::
:::

The goal for our "proof within a proof" is a negative statement, so proof by contradiction seems like a good start.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    have h2 : x âˆ‰ (âˆ… : Set U) := by
      by_contra h3
      **done::
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
U : Type
B : Set U
x : U
h1 : x âˆˆ âˆ… âˆ¨ x âˆˆ B
h3 : x âˆˆ âˆ…
âŠ¢ False
```
:::
:::

To see how to use the new assumption `h3`, we use the tactic `define at h3`.  The definition Lean gives for the statement `x âˆˆ âˆ…` is `False`.  In other words, Lean knows that, by the definition of `âˆ…`, the statement `x âˆˆ âˆ…` is false.  Since `False` is our goal, this completes the inner proof, and we can return to the main proof.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    have h2 : x âˆ‰ (âˆ… : Set U) := by
      by_contra h3
      define at h3  --Now h3 : False
      show False from h3
      done
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case h.mp
U : Type
B : Set U
x : U
h1 : x âˆˆ âˆ… âˆ¨ x âˆˆ B
h2 : Â¬x âˆˆ âˆ…
âŠ¢ x âˆˆ B
```
:::
:::

Now that we have established the claim `h2 : Â¬x âˆˆ âˆ…`, we can apply the disjunctive syllogism rule to `h1` and `h2` to reach the goal.  This completes the left-to-right direction of the biconditional proof, so we move on to the right-to-left direction.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    have h2 : x âˆ‰ (âˆ… : Set U) := by
      by_contra h3
      define at h3  --Now h3 : False
      show False from h3
      done
    disj_syll h1 h2  --Now h1 : x âˆˆ B
    show x âˆˆ B from h1
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case h.mpr
U : Type
B : Set U
x : U
âŠ¢ x âˆˆ B â†’ x âˆˆ âˆ… âˆª B
```
:::
:::

This direction of the biconditional proof is easier: once we introduce the assumption `h1 : x âˆˆ B`, our goal will be `x âˆˆ âˆ… âˆª B`, which means `x âˆˆ âˆ… âˆ¨ x âˆˆ B`, and we can prove it with the proof `Or.inr h1`.

::: {.inout}
::: {.inpt}
```lean
theorem empty_union {U : Type} (B : Set U) :
    (âˆ… : Set U) âˆª B = B := by
  apply Set.ext
  fix x : U
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : x âˆˆ (âˆ… : Set U) âˆª B
    define at h1
    have h2 : x âˆ‰ (âˆ… : Set U) := by
      by_contra h3
      define at h3  --Now h3 : False
      show False from h3
      done
    disj_syll h1 h2  --Now h1 : x âˆˆ B
    show x âˆˆ B from h1
    done
  Â· -- (â†)
    assume h1 : x âˆˆ B
    show x âˆˆ (âˆ… : Set U) âˆª B from Or.inr h1
    done
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

The second fact that was called "clear" in the proof from Example 3.6.2 was the equation `C âˆª D = D âˆª C`.  This looks like an instance of the commutativity of the union operator.  Let's prove that union is commutative.

::: {.inout}
::: {.inpt}
```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  
  **done::
```
:::

::: {.outpt}
```state
U : Type
X Y : Set U
âŠ¢ X âˆª Y = Y âˆª X
```
:::
:::

Once again, we begin with `apply Set.ext`, which converts the goal to `âˆ€ (x : U), x âˆˆ X âˆª Y â†” x âˆˆ Y âˆª X`, and then `fix x : U`.

::: {.inout}
::: {.inpt}
```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  apply Set.ext
  fix x : U
  **done::
```
:::

::: {.outpt}
```state
case h
U : Type
X Y : Set U
x : U
âŠ¢ x âˆˆ X âˆª Y â†” x âˆˆ Y âˆª X
```
:::
:::

To understand the goal better, we'll write out the definitions of the two sides of the biconditional.  We use an extension of the `define` tactic that allows us to write out the definition of just a part of a given or the goal.  The tactic `define : x âˆˆ X âˆª Y` will replace `x âˆˆ X âˆª Y` with its definition wherever it appears in the goal, and then `define : x âˆˆ Y âˆª X` will replace `x âˆˆ Y âˆª X` with its definition.  (As usual, you can add `at` to do the replacements in a given rather than the goal.)

::: {.inout}
::: {.inpt}
```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  apply Set.ext
  fix x : U
  define : x âˆˆ X âˆª Y
  define : x âˆˆ Y âˆª X
  **done::
```
:::

::: {.outpt}
```state
case h
U : Type
X Y : Set U
x : U
âŠ¢ x âˆˆ X âˆ¨ x âˆˆ Y â†”
>>  x âˆˆ Y âˆ¨ x âˆˆ X
```
:::
:::

By the way, there are similar extensions of all of the tactics `contrapos`, `demorgan`, `conditional`, `double_neg`, `bicond_neg`, and `quant_neg` that allow you to use a logical equivalence to rewrite just a part of a formula.  For example, if your goal is `P âˆ§ (Â¬Q â†’ R)`, then the tactic `contrapos : Â¬Q â†’ R` will change the goal to `P âˆ§ (Â¬R â†’ Q)`.  If you have a given `h : P â†’ Â¬âˆ€ (x : U), Q x`, then the tactic `quant_neg : Â¬âˆ€ (x : U), Q x at h` will change `h` to `h : P â†’ âˆƒ (x : U), Â¬Q x`.

Returning to our proof of `union_comm`: the goal is now `x âˆˆ X âˆ¨ x âˆˆ Y â†” x âˆˆ Y âˆ¨ x âˆˆ X`.  You could prove this by a somewhat tedious application of the rules for biconditionals and disjunctions that were discussed in the last two sections, and we invite you to try it.  But there is another possibility.  The goal now has the form `P âˆ¨ Q â†” Q âˆ¨ P`, which is the commutative law for "or" (see Section 1.2 of *HTPI*).  We saw in a previous example that Lean has, in its library, the associative law for "and"; it is called `and_assoc`.  Does Lean also know the commutative law for "or"?

Try typing `#check @or_` in VS Code.  After a few seconds, a pop-up window appears with possible completions of this command.  You will see `or_assoc` on the list, as well as `or_comm`.  Select `or_comm`, and you'll get this response:  `@or_comm : âˆ€ {a b : Prop}, a âˆ¨ b â†” b âˆ¨ a`.  Since `a` and `b` are implicit arguments in this theorem, you can use `or_comm` to prove any statement of the form `a âˆ¨ b â†” b âˆ¨ a`, where Lean will figure out for itself what `a` and `b` stand for.  In particular, `or_comm` will prove our current goal.

::: {.inout}
::: {.inpt}
```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  apply Set.ext
  fix x : U
  define : x âˆˆ X âˆª Y
  define : x âˆˆ Y âˆª X
  show x âˆˆ X âˆ¨ x âˆˆ Y â†” x âˆˆ Y âˆ¨ x âˆˆ X from or_comm
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

We have now proven the two statements that were said to be "clearly" true in the proof in Example 3.6.2 of *HTPI*, and we have given them names.  We can now use these theorems, in the file containing these proofs, to prove other theorems.  As with any theorem in Lean's library, you can use the `#check` command to confirm what these theorems say.  If you type `#check @empty_union` and `#check @union_comm`, you will get these results:

::: {.ind}
```
@empty_union : âˆ€ {U : Type} (B : Set U), âˆ… âˆª B = B
@union_comm : âˆ€ {U : Type} (X Y : Set U), X âˆª Y = Y âˆª X
```
:::

Notice that in both theorems we used curly braces when we introduced the type `U`, so it is an implicit argument and will not need to be specified when we apply the theorems.

We are finally ready to prove the theorem from Example 3.6.2.  Here is the theorem:

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by

  **done::

```
:::

::: {.outpt}
```state
U : Type
âŠ¢ âˆƒ! (A : Set U),
>>  âˆ€ (B : Set U),
>>    A âˆª B = B
```
:::
:::

The goal starts with `âˆƒ!`, so we use our new tactic, `exists_unique`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  **done::
```
:::

::: {.outpt}
```state
case Existence
U : Type
âŠ¢ âˆƒ (A : Set U),
>>  âˆ€ (B : Set U),
>>    A âˆª B = B
case Uniqueness
U : Type
âŠ¢ âˆ€ (A_1 A_2 : Set U),
>>  (âˆ€ (B : Set U),
>>      A_1 âˆª B = B) â†’
>>  (âˆ€ (B : Set U),
>>      A_2 âˆª B = B) â†’
>>  A_1 = A_2
```
:::
:::

We have two goals, labeled `Existence` and `Uniqueness`.  Imitating the proof from *HTPI*, we prove existence by using the value `âˆ…` for `A`.  It turns out that in this context, Lean is able to figure out which empty set we mean by `âˆ…`, so we don't need to specify the type.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  Â· -- Existence
    apply Exists.intro âˆ…
    **done::
  Â· -- Uniqueness

    **done::
  done
```
:::

::: {.outpt}
```state
case Existence
U : Type
âŠ¢ âˆ€ (B : Set U),
>>  âˆ… âˆª B = B
```
:::
:::

The goal is now precisely the statement of the theorem `empty_union`, so we can prove it by simply citing that theorem.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  Â· -- Existence
    apply Exists.intro âˆ…
    show âˆ€ (B : Set U), âˆ… âˆª B = B from empty_union
    done
  Â· -- Uniqueness

    **done::
  done
```
:::

::: {.outpt}
```state
case Uniqueness
U : Type
âŠ¢ âˆ€ (A_1 A_2 : Set U),
>>  (âˆ€ (B : Set U),
>>      A_1 âˆª B = B) â†’
>>  (âˆ€ (B : Set U),
>>      A_2 âˆª B = B) â†’
>>  A_1 = A_2
```
:::
:::

For the uniqueness proof, we begin by introducing arbitrary sets `C` and `D` and assuming `âˆ€ (B : Set U), C âˆª B = B` and `âˆ€ (B : Set U), D âˆª B = B`, exactly as in the *HTPI* proof.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  Â· -- Existence
    apply Exists.intro âˆ…
    show âˆ€ (B : Set U), âˆ… âˆª B = B from empty_union
    done
  Â· -- Uniqueness
    fix C : Set U; fix D : Set U
    assume h1 : âˆ€ (B : Set U), C âˆª B = B
    assume h2 : âˆ€ (B : Set U), D âˆª B = B
    **done::
  done
```
:::

::: {.outpt}
```state
case Uniqueness
U : Type
C D : Set U
h1 : âˆ€ (B : Set U),
>>  C âˆª B = B
h2 : âˆ€ (B : Set U),
>>  D âˆª B = B
âŠ¢ C = D
```
:::
:::

The next step in *HTPI* was to apply `h1` to `D`, and `h2` to `C`.  We do the same thing in Lean.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  Â· -- Existence
    apply Exists.intro âˆ…
    show âˆ€ (B : Set U), âˆ… âˆª B = B from empty_union
    done
  Â· -- Uniqueness
    fix C : Set U; fix D : Set U
    assume h1 : âˆ€ (B : Set U), C âˆª B = B
    assume h2 : âˆ€ (B : Set U), D âˆª B = B
    have h3 : C âˆª D = D := h1 D
    have h4 : D âˆª C = C := h2 C 
    **done::
  done
```
:::

::: {.outpt}
```state
case Uniqueness
U : Type
C D : Set U
h1 : âˆ€ (B : Set U),
>>  C âˆª B = B
h2 : âˆ€ (B : Set U),
>>  D âˆª B = B
h3 : C âˆª D = D
h4 : D âˆª C = C
âŠ¢ C = D
```
:::
:::

The goal can now be achieved by stringing together a sequence of equations:  `C = D âˆª C = C âˆª D = D`.  The first of these equations is `h4.symm`---that is, `h4` read backwards; the second follows from the commutative law for union; and the third is `h3`.  We saw in Section 3.4 that you can prove a biconditional statement in Lean by stringing together a sequence of biconditionals in a calculational proof.  Exactly the same method applies to equations.  Here is the complete proof of the theorem:

```lean
theorem Example_3_6_2 (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U),
    A âˆª B = B := by
  exists_unique
  Â· -- Existence
    apply Exists.intro âˆ…
    show âˆ€ (B : Set U), âˆ… âˆª B = B from empty_union
    done
  Â· -- Uniqueness
    fix C : Set U; fix D : Set U
    assume h1 : âˆ€ (B : Set U), C âˆª B = B
    assume h2 : âˆ€ (B : Set U), D âˆª B = B
    have h3 : C âˆª D = D := h1 D
    have h4 : D âˆª C = C := h2 C 
    show C = D from
      calc C
          = D âˆª C := h4.symm
        _ = C âˆª D := union_comm D C
        _ = D     := h3
    done
  done
```

Since the statement `âˆƒ! (x : U), P x` asserts both the existence and the uniqueness of an object satisfying the predicate `P`, we have the following strategy for using a given of this form:

#### To use a given of the form `âˆƒ! (x : U), P x`:

::: {.ind}
Introduce a new variable, say `a`, into the proof to stand for an object of type `U` for which `P a` is true.  You may also assert that `âˆ€ (x_1 x_2 : U), P x_1 â†’ P x_2 â†’ x_1 = x2`.
:::

If you have a given `h : âˆƒ! (x : U), P x`, then the tactic `obtain (a : U) (h1 : P a)` <br>`(h2 : âˆ€ (x_1 x_2 : U), P x_1 â†’ P x_2 â†’ x_1 = x_2) from h` will introduce into the tactic state a new variable `a` of type `U` and new givens `(h1 : P a)` and `(h2 : âˆ€ (x_1 x_2 : U), P x_1 â†’ P x_2 â†’ x_1 = x_2)`.  To illustrate the use of this tactic, let's prove the theorem in Example 3.6.4 of *HTPI*.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_4 (U : Type) (A B C : Set U)
    (h1 : âˆƒ (x : U), x âˆˆ A âˆ© B)
    (h2 : âˆƒ (x : U), x âˆˆ A âˆ© C)
    (h3 : âˆƒ! (x : U), x âˆˆ A) :
    âˆƒ (x : U), x âˆˆ B âˆ© C := by

  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
h2 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© C
h3 : âˆƒ! (x : U), x âˆˆ A
âŠ¢ âˆƒ (x : U), x âˆˆ B âˆ© C
```
:::
:::

We begin by applying the `obtain` tactic to `h1`, `h2`, and `h3`.  In the case of `h3`, we get an extra given asserting the uniqueness of the element of `A`.  We also write out the definitions of two of the new givens we obtain.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_4 (U : Type) (A B C : Set U)
    (h1 : âˆƒ (x : U), x âˆˆ A âˆ© B)
    (h2 : âˆƒ (x : U), x âˆˆ A âˆ© C)
    (h3 : âˆƒ! (x : U), x âˆˆ A) :
    âˆƒ (x : U), x âˆˆ B âˆ© C := by
  obtain (b : U) (h4 : b âˆˆ A âˆ© B) from h1
  obtain (c : U) (h5 : c âˆˆ A âˆ© C) from h2
  obtain (a : U) (h6 : a âˆˆ A) (h7 : âˆ€ (y z : U),
    y âˆˆ A â†’ z âˆˆ A â†’ y = z)  from h3
  define at h4; define at h5
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
h2 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© C
h3 : âˆƒ! (x : U), x âˆˆ A
b : U
h4 : b âˆˆ A âˆ§ b âˆˆ B
c : U
h5 : c âˆˆ A âˆ§ c âˆˆ C
a : U
h6 : a âˆˆ A
h7 : âˆ€ (y z : U),
>>  y âˆˆ A â†’ z âˆˆ A â†’ y = z
âŠ¢ âˆƒ (x : U), x âˆˆ B âˆ© C
```
:::
:::

The key to the rest of the proof is the observation that, by the uniqueness of the element of `A`, `b` must be equal to `c`.  To justify this conclusion, note that by two applications of universal instantiation, `h7 b c` is a proof of `b âˆˆ A â†’ c âˆˆ A â†’ b = c`, and therefore by two applications of modus ponens, `h7 b c h4.left h5.left` is a proof of `b = c`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_4 (U : Type) (A B C : Set U)
    (h1 : âˆƒ (x : U), x âˆˆ A âˆ© B)
    (h2 : âˆƒ (x : U), x âˆˆ A âˆ© C)
    (h3 : âˆƒ! (x : U), x âˆˆ A) :
    âˆƒ (x : U), x âˆˆ B âˆ© C := by
  obtain (b : U) (h4 : b âˆˆ A âˆ© B) from h1
  obtain (c : U) (h5 : c âˆˆ A âˆ© C) from h2
  obtain (a : U) (h6 : a âˆˆ A) (h7 : âˆ€ (y z : U),
    y âˆˆ A â†’ z âˆˆ A â†’ y = z)  from h3
  define at h4; define at h5
  have h8 : b = c := h7 b c h4.left h5.left
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
h2 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© C
h3 : âˆƒ! (x : U), x âˆˆ A
b : U
h4 : b âˆˆ A âˆ§ b âˆˆ B
c : U
h5 : c âˆˆ A âˆ§ c âˆˆ C
a : U
h6 : a âˆˆ A
h7 : âˆ€ (y z : U),
>>  y âˆˆ A â†’ z âˆˆ A â†’ y = z
h8 : b = c
âŠ¢ âˆƒ (x : U), x âˆˆ B âˆ© C
```
:::
:::

For our next step, we will need a new tactic.  Since we have `h8 : b = c`, we should be able to replace `b` with `c` anywhere it appears.  The tactic that allows us to do this called `rewrite`.  If `h` is a proof of any equation `s = t`, then `rewrite [h]` will replace all occurrences of `s` in the goal with `t`.  Notice that it is the left side of the equation that is replaced with the right side; if you want the replacement to go in the other direction, so that `t` is replaced with `s`, you can use `rewrite [â†h]`.  (Alternatively, since `h.symm` is a proof of `t = s`, you can use `rewrite [h.symm]`.)  You can also apply the `rewrite` tactic to biconditional statements.  If you have `h : P â†” Q`, then `rewrite [h]` will cause all occurrences of `P` in the goal to be replaced with `Q` (and `rewrite [â†h]` will replace `Q` with `P`).

As with many other tactics, you can add `at h'` to specify that the replacement should be done in the given `h'` rather than the goal.  In our case, `rewrite [h8] at h4` will change both occurrences of `b` in `h4` to `c`.

::: {.inout}
::: {.inpt}
```lean
theorem Example_3_6_4 (U : Type) (A B C : Set U)
    (h1 : âˆƒ (x : U), x âˆˆ A âˆ© B)
    (h2 : âˆƒ (x : U), x âˆˆ A âˆ© C)
    (h3 : âˆƒ! (x : U), x âˆˆ A) :
    âˆƒ (x : U), x âˆˆ B âˆ© C := by
  obtain (b : U) (h4 : b âˆˆ A âˆ© B) from h1
  obtain (c : U) (h5 : c âˆˆ A âˆ© C) from h2
  obtain (a : U) (h6 : a âˆˆ A) (h7 : âˆ€ (y z : U),
    y âˆˆ A â†’ z âˆˆ A â†’ y = z)  from h3
  define at h4; define at h5
  have h8 : b = c := h7 b c h4.left h5.left
  rewrite [h8] at h4
  **done::
```
:::

::: {.outpt}
```state
U : Type
A B C : Set U
h1 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© B
h2 : âˆƒ (x : U),
>>  x âˆˆ A âˆ© C
h3 : âˆƒ! (x : U), x âˆˆ A
b c : U
h4 : c âˆˆ A âˆ§ c âˆˆ B
h5 : c âˆˆ A âˆ§ c âˆˆ C
a : U
h6 : a âˆˆ A
h7 : âˆ€ (y z : U),
>>  y âˆˆ A â†’ z âˆˆ A â†’ y = z
h8 : b = c
âŠ¢ âˆƒ (x : U), x âˆˆ B âˆ© C
```
:::
:::

Now the right sides of `h4` and `h5` tell us that we can prove the goal by plugging in `c` for `x`.  Here is the complete proof:

```lean
theorem Example_3_6_4 (U : Type) (A B C : Set U)
    (h1 : âˆƒ (x : U), x âˆˆ A âˆ© B)
    (h2 : âˆƒ (x : U), x âˆˆ A âˆ© C)
    (h3 : âˆƒ! (x : U), x âˆˆ A) :
    âˆƒ (x : U), x âˆˆ B âˆ© C := by
  obtain (b : U) (h4 : b âˆˆ A âˆ© B) from h1
  obtain (c : U) (h5 : c âˆˆ A âˆ© C) from h2
  obtain (a : U) (h6 : a âˆˆ A) (h7 : âˆ€ (y z : U),
    y âˆˆ A â†’ z âˆˆ A â†’ y = z)  from h3
  define at h4; define at h5
  have h8 : b = c := h7 b c h4.left h5.left
  rewrite [h8] at h4
  show âˆƒ (x : U), x âˆˆ B âˆ© C from
    Exists.intro c (And.intro h4.right h5.right)
  done
```

You might want to compare the Lean proof above to the proof of this theorem as it appears in *HTPI*:

::: {.thm}
Suppose $A$, $B$, and $C$ are sets, $A$ and $B$ are not disjoint, $A$ and $C$ are not disjoint, and $A$ has exactly one element.  Then $B$ and $C$ are not disjoint
:::
::: {.proof}
Since $A$ and $B$ are not disjoint, we can let $b$ be something such that $b \in A$ and $b \in B$.  Similarly, since $A$ and $C$ are not disjoint, there is some object $c$ such that $c \in A$ and $c \in C$.  Since $A$ has only one element, we must have $b = c$.  Thus $b = c \in B \cap C$ and therefore $B$ and $C$ are not disjoint. [&nbsp;â–¡]{.excl}\qedhere
:::

Before ending this section, we return to the question of how you can tell if a theorem you want to use is in Lean's library.  In an earlier example, we guessed that the commutative law for "or" might be in Lean's library, and we were then able to use the `#check` command to confirm it.  But there is another technique that we could have used: the tactic `library_search`.  Let's return to our proof of the theorem `union_comm`, which started like this:

::: {.inout}
::: {.inpt}
```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  apply Set.ext
  fix x : U
  define : x âˆˆ X âˆª Y
  define : x âˆˆ Y âˆª X
  **done::
```
:::

::: {.outpt}
```state
case h
U : Type
X Y : Set U
x : U
âŠ¢ x âˆˆ X âˆ¨ x âˆˆ Y â†”
>>  x âˆˆ Y âˆ¨ x âˆˆ X
```
:::
:::

Now let's give the `library_search` tactic a try.

```lean
theorem union_comm {U : Type} (X Y : Set U) :
    X âˆª Y = Y âˆª X := by
  apply Set.ext
  fix x : U
  define : x âˆˆ X âˆª Y
  define : x âˆˆ Y âˆª X
  ##library_search::
  done
```

It takes a few seconds for Lean to search its library of theorems, but eventually a blue squiggle appears under `library_search`, indicating that the tactic has produced an answer.  You will find the answer in the Infoview pane:  `exact or_comm' (x âˆˆ X) (x âˆˆ Y)`.  The word `exact` is the name of a tactic that we have not discussed; it is a shorthand for `show _ from`, where the blank gets filled in with the goal.  Thus, you can think of `library_search`'s answer as a shortened form of the tactic

::: {.ind}
```
show x âˆˆ X âˆ¨ x âˆˆ Y â†” x âˆˆ Y âˆ¨ x âˆˆ X from or_comm' (x âˆˆ X) (x âˆˆ Y)
```
:::

Usually your proof will be more readable if you use the `show` tactic to state explicitly the goal that is being proven.  This also gives Lean a chance to correct you if you have become confused about what goal you are proving.  But sometimes---for example, if the goal is very long---it is convenient to use the `exact` tactic instead.  You might think of `exact` as meaning "the following is a term-mode proof that is exactly what is needed to prove the goal."

The `library_search` tactic has not only come up with a suggested tactic, it has applied that tactic, and the proof is now complete.  You can confirm that the tactic completes the proof by replacing the line `library_search` in the proof with either `library_search`'s suggested `exact` tactic or the `show` tactic displayed above.

But what is `or_comm'`?  The command `#check @or_comm'` gives the result

::: {.ind}
```
or_comm' : âˆ€ (a b : Prop), a âˆ¨ b â†” b âˆ¨ a
```
:::

So `or_comm'` is the same as `or_comm`, except that the arguments `a` and `b` are not implicit; that's why `library_search` had to specify values for those arguments in its answer.  The `#check` command also produces a suggestion that we should use `or_comm` instead.

The `library_search` tactic is somewhat unpredictable; sometimes it is able to find the right theorem in the library, and sometimes it isn't.  But it is always worth a try.  Other tactics that may be helpful are `suggest` and `hint`.

### Exercises

::: {.numex arguments="1"}
```lean
theorem Exercise_3_4_15 (U : Type) (B : Set U) (F : Set (Set U)) :
    â‹ƒâ‚€{X : Set U | âˆƒ (A : Set U), A âˆˆ F âˆ§ X = A \ B}
      âŠ† â‹ƒâ‚€(F \ ð’« B) := sorry
```
:::

::: {.numex arguments="2"}
```lean
theorem Exercise_3_5_9 (U : Type) (A B : Set U)
    (h1 : ð’« (A âˆª B) = ð’« A âˆª ð’« B) : A âŠ† B âˆ¨ B âŠ† A := by
  --Hint:  Start like this:
  have h2 : A âˆª B âˆˆ ð’« (A âˆª B) := sorry
  
  **done::
```
:::

::: {.numex arguments="3"}
```lean
theorem Exercise_3_6_6b (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U), A âˆª B = A := sorry
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_6_7b (U : Type) :
    âˆƒ! (A : Set U), âˆ€ (B : Set U), A âˆ© B = A := sorry
```
:::

::: {.numex arguments="5"}
```lean
theorem Exercise_3_6_8a (U : Type) : âˆ€ (A : Set U),
    âˆƒ! (B : Set U), âˆ€ (C : Set U), C \ A = C âˆ© B := sorry
```
:::

::: {.numex arguments="6"}
```lean
theorem Exercise_3_6_10 (U : Type) (A : Set U)
    (h1 : âˆ€ (F : Set (Set U)), â‹ƒâ‚€F = A â†’ A âˆˆ F) :
    âˆƒ! (x : U), x âˆˆ A := by
  --Hint:  Start like this:
  let F0 := {X : Set U | X âŠ† A âˆ§ âˆƒ! (x : U), x âˆˆ X}
  --Now F0 is in the tactic state, with the definition above
  have h2 : â‹ƒâ‚€F0 = A := sorry
  
  **done::
```
:::

## 3.7. More Examples of Proofs

It is finally time to discuss proofs involving algebraic reasoning.  Lean has types for several different kinds of numbers.  `Nat` is the type of natural numbers---that is, the numbers 0, 1, 2, ....  `Int` is the type of integers, `Rat` is the type of rational numbers, `Real` is the type of real numbers, and `Complex` is the type of complex numbers.  Lean also uses the notation `â„•`, `â„¤`, `â„š`, `â„`, and `â„‚` for these types.  To write formulas involving arithmetic operations, you should use the symbols `+` for addition, `-` for subtraction, `*` for multiplication, `/` for division, and `^` for exponentiation.  To see what's involved in proving theorems about numbers in Lean, we'll turn to a few examples from earlier in Chapter 3 of *HTPI*.

We begin with Theorem 3.3.7, which concerns divisibility of integers.  As in *HTPI*, for integers `x` and `y`, we will write `x âˆ£ y` to mean that `x` divides `y`, or `y` is divisible by `x`.  The formal definition is that `x âˆ£ y` means that there is an integer `k` such that `y = x * k`.  For example, `3 âˆ£ 12`, since `12 = 3 * 4`.  Lean knows this notation, but there is an important warning: to type the vertical line that means "divides," you must type `\|`, not simply `|`.  (There are two slightly different vertical line symbols, and you have to look closely to see that they are different: `|` and `âˆ£`.  It is the second one that means "divides" in Lean, and to enter it you must type `\|`.)  Here is Theorem 3.3.7, written using our usual rephrasing of a statement of the form `A âˆ§ B â†’ C` as `A â†’ B â†’ C`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  
  **done::
```
:::

::: {.outpt}
```state
âŠ¢ âˆ€ (a b c : â„¤),
>>  a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c
```
:::
:::

Of course, we begin the proof by introducing arbitrary integers `a`, `b`, and `c`, and assuming `a âˆ£ b` and `b âˆ£ c`.  We also write out the definitions of our assumptions and the goal.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  **done::
```
:::

::: {.outpt}
```state
a b c : â„¤
h1 : âˆƒ (c : â„¤),
>>  b = a * c
h2 : âˆƒ (c_1 : â„¤),
>>  c = b * c_1
âŠ¢ âˆƒ (c_1 : â„¤),
>>  c = a * c_1
```
:::
:::

We always use existential givens right away, so we use `h1` and `h2` to introduce two new variables, `m` and `n`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  obtain (m : Int) (h3 : b = a * m) from h1
  obtain (n : Int) (h4 : c = b * n) from h2
  **done::
```
:::

::: {.outpt}
```state
a b c : â„¤
h1 : âˆƒ (c : â„¤),
>>  b = a * c
h2 : âˆƒ (c_1 : â„¤),
>>  c = b * c_1
m : â„¤
h3 : b = a * m
n : â„¤
h4 : c = b * n
âŠ¢ âˆƒ (c_1 : â„¤),
>>  c = a * c_1
```
:::
:::

If we substitute the value for `b` given in `h3` into `h4`, we will see how to reach the goal.  Of course, the `rewrite` tactic is what we need for this.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  obtain (m : Int) (h3 : b = a * m) from h1
  obtain (n : Int) (h4 : c = b * n) from h2
  rewrite [h3] at h4   --h4: c = a * m * n
  **done::
```
:::

::: {.outpt}
```state
a b c : â„¤
h1 : âˆƒ (c : â„¤),
>>  b = a * c
h2 : âˆƒ (c_1 : â„¤),
>>  c = b * c_1
m : â„¤
h3 : b = a * m
n : â„¤
h4 : c = a * m * n
âŠ¢ âˆƒ (c_1 : â„¤),
>>  c = a * c_1
```
:::
:::

Looking at `h4`, we see that the value we should use for `c_1` in the goal is `m * n`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  obtain (m : Int) (h3 : b = a * m) from h1
  obtain (n : Int) (h4 : c = b * n) from h2
  rewrite [h3] at h4   --h4: c = a * m * n
  apply Exists.intro (m * n)
  **done::
```
:::

::: {.outpt}
```state
a b c : â„¤
h1 : âˆƒ (c : â„¤),
>>  b = a * c
h2 : âˆƒ (c_1 : â„¤),
>>  c = b * c_1
m : â„¤
h3 : b = a * m
n : â„¤
h4 : c = a * m * n
âŠ¢ c = a * (m * n)
```
:::
:::

Comparing `h4` to the goal, you might think that we can finish the proof with `show c = a * (m * n) from h4`.  But if you try it, you will get an error message.  What's the problem?  The difference in the parentheses is the clue.  Lean groups the arithmetic operations `+`, `-`, `*`, and `/` to the left, so `h4` means `h4 : c = (a * m) * n`, which is not quite the same as the goal.  To prove the goal, we will need to apply the associative law for multiplication.

We have already seen that `and_assoc` is Lean's name for the associative law for "and".  Perhaps you can guess that the name for the associative law for multiplication is `mul_assoc`.  If you type `#check @mul_assoc`, Lean's response will be:

::: {.ind}
```
@mul_assoc : âˆ€ {G : Type u_1} [inst : Semigroup G] (a b c : G),
              a * b * c = a * (b * c)
```
:::

The implicit arguments in this cases are a little complicated (the expression `[inst : Semigroup G]` represents yet another kind of implicit argument).  But what they mean is that `mul_assoc` can be used to prove any statement of the form `âˆ€ (a b c : U), a * b * c = a * (b * c)`, as long as `U` is a type that has an associative multiplication operation.  In particular, `mul_assoc` can be used as a proof of `âˆ€ (a b c : Int), a * b * c = a * (b * c)`.  (There are also versions of this theorem for particular number types.  You can use the `#check` command to verify the theorems `Nat.mul_assoc : âˆ€ (a b c : â„•), a * b * c = a * (b * c)`, `Int.mul_assoc : âˆ€ (a b c : â„¤), a * b * c = a * (b * c)`, and so on.)

Returning to our proof of Theorem 3.3.7, by three applications of universal instantiation, `mul_assoc a m n` is a proof of `a * m * n = a * (m * n)`, and that is exactly what we need to finish the proof.  The tactic `rewrite [mul_assoc a m n] at h4` will replace `a * m * n` in `h4` with `a * (m * n)`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  obtain (m : Int) (h3 : b = a * m) from h1
  obtain (n : Int) (h4 : c = b * n) from h2
  rewrite [h3] at h4   --h4: c = a * m * n
  apply Exists.intro (m * n)
  rewrite [mul_assoc a m n] at h4
  **done::
```
:::

::: {.outpt}
```state
a b c : â„¤
h1 : âˆƒ (c : â„¤),
>>  b = a * c
h2 : âˆƒ (c_1 : â„¤),
>>  c = b * c_1
m : â„¤
h3 : b = a * m
n : â„¤
h4 : c = a * (m * n)
âŠ¢ c = a * (m * n)
```
:::
:::

By the way, this is a case in which Lean could have figured out some details on its own.  If we had used `rewrite [mul_assoc _ _ _] at h4`, then Lean would have figured out that the blanks had to be filled in with `a`, `m`, and `n`.  And as with the `apply` tactic, blanks at the end of `rewrite` rules can be left out, so even `rewrite [mul_assoc] at h4` would have worked.

Of course, now `h4` really does match the goal exactly, so we can use it to complete the proof.

```lean
theorem Theorem_3_3_7 :
    âˆ€ (a b c : Int), a âˆ£ b â†’ b âˆ£ c â†’ a âˆ£ c := by
  fix a : Int; fix b : Int; fix c : Int
  assume h1 : a âˆ£ b; assume h2 : b âˆ£ c
  define at h1; define at h2; define
  obtain (m : Int) (h3 : b = a * m) from h1
  obtain (n : Int) (h4 : c = b * n) from h2
  rewrite [h3] at h4   --h4: c = a * m * n
  apply Exists.intro (m * n)
  rewrite [mul_assoc a m n] at h4
  show c = a * (m * n) from h4
  done
```

As usual, you might find it instructive to compare the Lean proof above to the proof of this theorem in *HTPI*.

For our next example, we'll do a somewhat more complex proof concerning divisibility.  Here is the proof from *HTPI*.

::: {.nthm arguments="Theorem 3.4.7"}
For every integer $n$, $6 \mid n$ iff $2 \mid n$ and $3 \mid n$.
:::
::: {.proof}
Let $n$ be an arbitrary integer.

($\to$) Suppose $6 \mid n$.  Then we can choose an integer $k$ such that $6k=n$.  Therefore $n = 6k = 2(3k)$, so $2 \mid n$, and similarly $n = 6k = 3(2k)$, so $3 \mid n$.

($\leftarrow$) Suppose $2 \mid n$ and $3 \mid n$.  Then we can choose integers $j$ and $k$ such that $n = 2j$ and $n = 3k$.  Therefore $6(j-k) = 6j - 6k = 3(2j) - 2(3k) = 3n - 2n = n$, so $6 \mid n$. [&nbsp;â–¡]{.excl}\qedhere
:::

Let's try writing the proof in Lean.  We use exactly the same strategy as in the *HTPI* proof: we begin by fixing an arbitrary integer `n`, and then we prove the two directions of the biconditional separately.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  **done::
```
:::

::: {.outpt}
```state
case mp
n : â„¤
âŠ¢ 6 âˆ£ n â†’ 2 âˆ£ n âˆ§ 3 âˆ£ n
case mpr
n : â„¤
âŠ¢ 2 âˆ£ n âˆ§ 3 âˆ£ n â†’ 6 âˆ£ n
```
:::
:::

For the left-to-right direction, we assume `6 âˆ£ n`, and since the definition of this assumption is an existential statement, we immediately apply existential instantiation.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    **done::
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp
n : â„¤
h1 : âˆƒ (c : â„¤),
>>  n = 6 * c
k : â„¤
h2 : n = 6 * k
âŠ¢ 2 âˆ£ n âˆ§ 3 âˆ£ n
```
:::
:::

Our goal is now a conjunction, so we prove the two conjuncts separately.  Focusing just on the first one, `2 âˆ£ n`, we write out the definition to decide how to proceed.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    apply And.intro
    Â· -- Proof that 2 âˆ£ n
      define
      **done::
    Â· -- Proof that 3 âˆ£ n

      **done::
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp.left
n : â„¤
h1 : âˆƒ (c : â„¤),
>>  n = 6 * c
k : â„¤
h2 : n = 6 * k
âŠ¢ âˆƒ (c : â„¤), n = 2 * c
```
:::
:::

Since we have `n = 6 * k = 2 * 3 * k`, it looks like `3 * k` is the value we should use for `c`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    apply And.intro
    Â· -- Proof that 2 âˆ£ n
      define
      apply Exists.intro (3 * k)
      **done::
    Â· -- Proof that 3 âˆ£ n

      **done::
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp.left
n : â„¤
h1 : âˆƒ (c : â„¤),
>>  n = 6 * c
k : â„¤
h2 : n = 6 * k
âŠ¢ n = 2 * (3 * k)
```
:::
:::

Once again, if you think carefully about it, you will see that in order to deduce the goal from `h2`, we will need to use the associativity of multiplication to rewrite the goal as `n = 2 * 3 * k`.  As we have already seen, `mul_assoc 2 3 k` is a proof of `2 * 3 * k = 2 * (3 * k)`.  Since we want to replace the right side of this equation with the left in the goal, we'll use the tactic `rewrite [â†mul_assoc 2 3 k]`.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    apply And.intro
    Â· -- Proof that 2 âˆ£ n
      define
      apply Exists.intro (3 * k)
      rewrite [â†mul_assoc 2 3 k]
      **done::
    Â· -- Proof that 3 âˆ£ n

      **done::
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp.left
n : â„¤
h1 : âˆƒ (c : â„¤),
>>  n = 6 * c
k : â„¤
h2 : n = 6 * k
âŠ¢ n = 2 * 3 * k
```
:::
:::

Do we have to convince Lean that `2 * 3 = 6`?  No, remember that Lean works out definitions on its own.  Lean knows the definition of multiplication, and it knows that, according to that definition, `2 * 3` is equal to `6`.  So it regards `n = 6 * k` and `n = 2 * 3 * k` as definitionally equal, and therefore it will recognize `h2` as a proof of the goal.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    apply And.intro
    Â· -- Proof that 2 âˆ£ n
      define
      apply Exists.intro (3 * k)
      rewrite [â†mul_assoc 2 3 k]
      show n = 2 * 3 * k from h2
      done
    Â· -- Proof that 3 âˆ£ n

      **done::
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mp.right
n : â„¤
h1 : âˆƒ (c : â„¤),
>>  n = 6 * c
k : â„¤
h2 : n = 6 * k
âŠ¢ 3 âˆ£ n
```
:::
:::

The proof of the next goal, `3 âˆ£ n`, is similar, and it completes the left-to-right direction of the biconditional.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    assume h1 : 6 âˆ£ n; define at h1
    obtain (k : Int) (h2 : n = 6 * k) from h1
    apply And.intro
    Â· -- Proof that 2 âˆ£ n
      define
      apply Exists.intro (3 * k)
      rewrite [â†mul_assoc 2 3 k]
      show n = 2 * 3 * k from h2
      done
    Â· -- Proof that 3 âˆ£ n
      define
      apply Exists.intro (2 * k)
      rewrite [â†mul_assoc 3 2 k]
      show n = 3 * 2 * k from h2
      done
    done
  Â· -- (â†)

    **done::
  done
```
:::

::: {.outpt}
```state
case mpr
n : â„¤
âŠ¢ 2 âˆ£ n âˆ§ 3 âˆ£ n â†’ 6 âˆ£ n
```
:::
:::

For the right-to-left direction, we begin by assuming `2 âˆ£ n âˆ§ 3 âˆ£ n`.  We write out the definitions of `2 âˆ£ n` and `3 âˆ£ n`, and since this gives us two existential givens, we apply existential instantiation twice.  To save space, we won't repeat the proof of the first half of the proof in the displays below.

::: {.inout}
::: {.inpt}
```lean
theorem Theorem_3_4_7 :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    ...
  Â· -- (â†)
    assume h1
    have h2 := h1.left
    have h3 := h1.right
    define at h2; define at h3; define
    obtain (j : Int) (h4 : n = 2 * j) from h2
    obtain (k : Int) (h5 : n = 3 * k) from h3
    **done::
  done
```
:::

::: {.outpt}
```state
case mpr
n : â„¤
h1 : 2 âˆ£ n âˆ§ 3 âˆ£ n
h2 : âˆƒ (c : â„¤),
>>  n = 2 * c
h3 : âˆƒ (c : â„¤),
>>  n = 3 * c
j : â„¤
h4 : n = 2 * j
k : â„¤
h5 : n = 3 * k
âŠ¢ âˆƒ (c : â„¤),
>>  n = 6 * c
```
:::
:::

The next step in the *HTPI* proof is a string of equations that proves $6(j - k) = n$, which establishes that $6 \mid n$.  Let's try to do the same thing in Lean, using a calculational proof:

::: {.inout}
::: {.inpt}
```lean
theorem ??Theorem_3_4_7:: :
    âˆ€ (n : Int), 6 âˆ£ n â†” 2 âˆ£ n âˆ§ 3 âˆ£ n := by
  fix n : Int
  apply Iff.intro
  Â· -- (â†’)
    ...
  Â· -- (â†)
    assume h1
    have h2 := h1.left
    have h3 := h1.right
    define at h2; define at h3; define
    obtain (j : Int) (h4 : n = 2 * j) from h2
    obtain (k : Int) (h5 : n = 3 * k) from h3
    have h6 : 6 * (j - k) = n :=
      calc 6 * (j - k)
          = 6 * j - 6 * k := sorry
        _ = 3 * (2 * j) - 2 * (3 * k) := sorry
        _ = 3 * n - 2 * n := sorry
        _ = (3 - 2) * n := sorry
        _ = n := sorry
    show âˆƒ (c : Int), n = 6 * c from
      Exists.intro (j - k) h6.symm
    done
  done
```
:::

::: {.outpt}
```state
>>No goals
```
:::
:::

Sometimes the easiest way to write a calculational proof is to justify each line with `sorry` and then go back and fill in real justifications.  Lean has accepted the proof above, so we know that we'll have a complete proof if we can replace each `sorry` with a justification.

To justify the first line of the calculational proof, try replacing `sorry` with `by library_search`.  Lean comes up with a justification:  `exact mul_sub_left_distrib 6 j k`.  The command `#check @mul_sub_left_distrib` tells us that the theorem `mul_sub_left_distrib` means

::: {.ind}
```
@mul_sub_left_distrib : âˆ€ {Î± : Type u_1} [inst : NonUnitalNonAssocRing Î±]
                          (a b c : Î±), a * (b - c) = a * b - a * c
```
:::

Don't worry too much about the confusing implicit arguments in the first line; they are implicit, so you won't have to supply them.  The second line tells us that we can fill in `mul_sub_left_distrib 6 j k` as a proof of the first equation.

It looks like we'll have to use the associativity of multiplication again to prove the second equation, but it will take more than one step.  Let's try writing a tactic-mode proof.  In the display below, we'll just focus on the calculational proof.

::: {.inout}
::: {.inpt}
```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 6 * j - 6 * k :=
        mul_sub_left_distrib 6 j k
    _ = 3 * (2 * j) - 2 * (3 * k) :=
        by

          **done::
    _ = 3 * n - 2 * n := sorry
    _ = (3 - 2) * n := sorry
    _ = n := sorry
```
:::

::: {.outpt}
```state
n : â„¤
h1 : 2 âˆ£ n âˆ§ 3 âˆ£ n
h2 : âˆƒ (c : â„¤),
>>  n = 2 * c
h3 : âˆƒ (c : â„¤),
>>  n = 3 * c
j : â„¤
h4 : n = 2 * j
k : â„¤
h5 : n = 3 * k
âŠ¢ 6 * j - 6 * k =
>>  3 * (2 * j) -
>>    2 * (3 * k)
```
:::
:::

To justify the second equation, we'll have to use associativity to rewrite both `3 * (2 * j)` as `3 * 2 * j` and also `2 * (3 * k)` as `2 * 3 * k`.  So we apply the `rewrite` tactic to both of the proofs `mul_assoc 3 2 j : 3 * 2 * j = 3 * (2 * j)` and `mul_assoc 2 3 k : 2 * 3 * k = 2 * (3 * k)`:

::: {.inout}
::: {.inpt}
```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 6 * j - 6 * k :=
        mul_sub_left_distrib 6 j k
    _ = 3 * (2 * j) - 2 * (3 * k) :=
        by
          rewrite [â†mul_assoc 3 2 j]
          rewrite [â†mul_assoc 2 3 k]
          **done::
    _ = 3 * n - 2 * n := sorry
    _ = (3 - 2) * n := sorry
    _ = n := sorry
```
:::

::: {.outpt}
```state
n : â„¤
h1 : 2 âˆ£ n âˆ§ 3 âˆ£ n
h2 : âˆƒ (c : â„¤),
>>  n = 2 * c
h3 : âˆƒ (c : â„¤),
>>  n = 3 * c
j : â„¤
h4 : n = 2 * j
k : â„¤
h5 : n = 3 * k
âŠ¢ 6 * j - 6 * k =
>>  3 * 2 * j - 
>>    2 * 3 * k
```
:::
:::

To finish off the justification of the second equation, we'll use the theorem `Eq.refl`.  The command `#check @Eq.refl` gives the result `@Eq.refl : âˆ€ {Î± : Sort u_1} (a : Î±), a = a`.  Ignoring the implicit argument `Î±`, this should remind you of the theorem `Iff.refl : âˆ€ (a : Prop), a â†” a`.  Recall that we were able to use `Iff.refl _` to prove not only any statement of the form `a â†” a`, but also statements of the form `a â†” a'`, where `a` and `a'` are definitionally equal.  Similarly, `Eq.refl _` will prove any equation of the form `a = a'`, where `a` and `a'` are definitionally equal.  Since Lean knows that, by definition, `3 * 2 = 6` and `2 * 3 = 6`, the goal has this form.  Thus we can complete the proof with the tactic `show 6 * j - 6 * k = 3 * 2 * j - 2 * 3 * k from Eq.refl _`.  As we saw earlier, a shorter version of this would be `exact Eq.refl _`.  But this situation comes up often enough that there is an even shorter version: the tactic `rfl` can be used as a shorthand for either `exact Eq.refl _` or `exact Iff.refl _`.  In other words, in a tactic-mode proof, if the goal has one of the forms `a = a'` or `a â†” a'`, where `a` and `a'` are definitionally equal, then the tactic `rfl` will prove the goal.  So `rfl` will finish off the justification of the second equation, and we can move on to the third.

::: {.inout}
::: {.inpt}
```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 6 * j - 6 * k :=
        mul_sub_left_distrib 6 j k
    _ = 3 * (2 * j) - 2 * (3 * k) :=
        by
          rewrite [â†mul_assoc 3 2 j]
          rewrite [â†mul_assoc 2 3 k]
          rfl
          done
    _ = 3 * n - 2 * n :=
        by

          **done::
    _ = (3 - 2) * n := sorry
    _ = n := sorry
```
:::
::: {.outpt}
```state
n : â„¤
h1 : 2 âˆ£ n âˆ§ 3 âˆ£ n
h2 : âˆƒ (c : â„¤),
>>  n = 2 * c
h3 : âˆƒ (c : â„¤),
>>  n = 3 * c
j : â„¤
h4 : n = 2 * j
k : â„¤
h5 : n = 3 * k
âŠ¢ 3 * (2 * j) -
>>  2 * (3 * k) =
>>    3 * n - 2 * n
```
:::
:::

To justify the third equation we have to substitute `n` for both `2 * j` and `3 * k`.  We can use `h4` and `h5` in the rewrite tactic to do this.  In fact, we can do it in one step: you can put a list of proofs of equations or biconditionals inside the brackets, and the `rewrite` tactic will perform all of the replacements, one after another.  In our case, the tactic `rewrite [h4, h5]` will first replace `2 * j` in the goal with `n`, and then it will replace `3 * k` with `n`.

::: {.inout}
::: {.inpt}
```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 6 * j - 6 * k :=
        mul_sub_left_distrib 6 j k
    _ = 3 * (2 * j) - 2 * (3 * k) :=
        by
          rewrite [â†mul_assoc 3 2 j]
          rewrite [â†mul_assoc 2 3 k]
          rfl
          done
    _ = 3 * n - 2 * n :=
        by
          rewrite [â†h4, â†h5]
          **done::
    _ = (3 - 2) * n := sorry
    _ = n := sorry
```
:::

::: {.outpt}
```state
n : â„¤
h1 : 2 âˆ£ n âˆ§ 3 âˆ£ n
h2 : âˆƒ (c : â„¤),
>>  n = 2 * c
h3 : âˆƒ (c : â„¤),
>>  n = 3 * c
j : â„¤
h4 : n = 2 * j
k : â„¤
h5 : n = 3 * k
âŠ¢ 3 * n - 2 * n =
>>  3 * n - 2 * n
```
:::
:::

Of course, the `rfl` tactic will now finish off the justification of the third equation.

The fourth equation is `3 * n - 2 * n = (3 - 2) * n`.  It looks like the algebraic law we need to justify this is a lot like the one that was used in the first equation, but with the multiplication to the right of the subtraction rather than to the left.  It shouldn't be surprising, therefore, that the name of the theorem we need is `mul_sub_right_distrib`.  The command `#check @mul_sub_right_distrib` gives the response

:::{.ind}
```
@mul_sub_right_distrib : âˆ€ {Î± : Type u_1} [inst : NonUnitalNonAssocRing Î±]
                          (a b c : Î±), (a - b) * c = a * c - b * c
```
:::

so `mul_sub_right_distrib 3 2 n` is a proof of `(3 - 2) * n = 3 * n - 2 * n`.  But the fourth equation has the sides of this equation reversed, so to justify it we need `(mul_sub_right_distrib 3 2 n).symm`.

Finally, the fifth equation is `(3 - 2) * n = n`.  Why is this true?  Because it is definitionally equal to `1 * n = n`.  Is there a theorem to justify this last equation?  One way to find the answer is to type in this example:

```lean
example (n : Int) : 1 * n = n := by ##library_search::
```

Lean responds with `exact one_mul n`, and `#check @one_mul` yields

::: {.ind}
```
@one_mul : âˆ€ {M : Type u_1} [inst : MulOneClass M] (a : M), 1 * a = a
```
:::

So `one_mul n` should justify the last equation.  Here's the complete calculational proof, where we have shortened the second step a bit by doing both `rewrite`s in one step.  When a tactic proof is short enough that it can be written on one line, we generally leave off `done`.

```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 6 * j - 6 * k :=
        mul_sub_left_distrib 6 j k
    _ = 3 * (2 * j) - 2 * (3 * k) :=
        by rewrite [â†mul_assoc 3 2 j, â†mul_assoc 2 3 k]; rfl
    _ = 3 * n - 2 * n := by rewrite [â†h4, â†h5]; rfl
    _ = (3 - 2) * n := (mul_sub_right_distrib 3 2 n).symm
    _ = n := one_mul n
```

Whew!  This example illustrates why algebraic reasoning in Lean can be difficult.  But one reason why this proof was challenging is that we justified all of our steps from basic algebraic principles.  Fortunately, there are more powerful tactics that can automate some algebraic reasoning.  For example, the tactic `ring` can combine algebraic laws involving addition, subtraction, multiplication, and exponentiation with natural number exponents to prove many equations in one step.  Also, the tactic `rw` is a variant of `rewrite` that automatically applies `rfl` after the rewriting if it can be used to finish the proof.  Here's a shortened version of our calculational proof that uses these tactics.

```lean
have h6 : 6 * (j - k) = n :=
  calc 6 * (j - k)
      = 3 * (2 * j) - 2 * (3 * k) := by ring
    _ = 3 * n - 2 * n := by rw [â†h4, â†h5]
    _ = n := by ring
```

### Exercises

::: {.numex arguments="1"}
```lean
theorem Exercise_3_3_18a (a b c : Int)
    (h1 : a âˆ£ b) (h2 : a âˆ£ c) : a âˆ£ (b + c) := sorry
```
:::

2\.  Complete the following proof by justifying the steps in the calculational proof.  Remember that you can use the tactic `demorgan : ...` to apply one of De Morgan's laws to just a part of the goal.  You may also find the theorem `and_or_left` useful.  (Use `#check` to see what the theorem says.)

```lean
theorem Exercise_3_4_6 (U : Type) (A B C : Set U) :
    A \ (B âˆ© C) = (A \ B) âˆª (A \ C) := by
  apply Set.ext
  fix x : U
  show x âˆˆ A \ (B âˆ© C) â†” x âˆˆ A \ B âˆª A \ C from
    calc x âˆˆ A \ (B âˆ© C)
        â†” x âˆˆ A âˆ§ Â¬(x âˆˆ B âˆ§ x âˆˆ C) := sorry
      _ â†” x âˆˆ A âˆ§ (Â¬x âˆˆ B âˆ¨ Â¬x âˆˆ C) := sorry  
      _ â†” (x âˆˆ A âˆ§ Â¬x âˆˆ B) âˆ¨ (x âˆˆ A âˆ§ Â¬x âˆˆ C) := sorry
      _ â†” x âˆˆ (A \ B) âˆª (A \ C) := sorry
```

::: {.mdsk}
:::

For the next exercise you will need the following definitions:

```lean
def even (n : Int) : Prop := âˆƒ (k : Int), n = 2 * k
def odd (n : Int) : Prop := âˆƒ (k : Int), n = 2 * k + 1
```

::: {.numex arguments="3"}
```lean
theorem Exercise_3_4_10 (x y : Int)
    (h1 : odd x) (h2 : odd y) : even (x - y) := sorry
```
:::

::: {.numex arguments="4"}
```lean
theorem Exercise_3_4_27a :
    âˆ€ (n : Int), 15 âˆ£ n â†” 3 âˆ£ n âˆ§ 5 âˆ£ n := sorry
```
:::